/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Accompanying;
import Classes.External;
import Classes.Internal;
import Classes.Umrah;
import static Form.InternalSektion.TXTFinalCoast;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class AccompanyingPage extends javax.swing.JFrame {

    /**
     * Creates new form AccompanyingPage
     */
    Accompanying ac = new Accompanying();
    Internal in = new Internal();
    External ex = new External();
    Umrah u = new Umrah();
    private String URL;
    
    public AccompanyingPage() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLImage, 750, 340);
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLImage1, 750, 340);
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLImage2, 750, 340);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        Internal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InternalAdd = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(180);
        jLabel3 = new javax.swing.JLabel();
        TXTSSN = new controls.JTextBox(180);
        jLabel4 = new javax.swing.JLabel();
        TXTTele = new controls.JTextBox(180);
        jLabel5 = new javax.swing.JLabel();
        TXTCode = new controls.JTextBox(180);
        jLabel6 = new javax.swing.JLabel();
        TXTChair = new controls.JTextBox(180);
        jLabel7 = new javax.swing.JLabel();
        TXTParent = new controls.JTextBox(180);
        BTNSeate1 = new controls.JMybotton();
        BTNAdd = new controls.JMybotton();
        BTNReset1 = new controls.JMybotton();
        LBLImage = new javax.swing.JLabel();
        Umrah = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        UmrahAdd = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TXTName1 = new controls.JTextBox(180);
        jLabel9 = new javax.swing.JLabel();
        TXTPassport = new controls.JTextBox(180);
        jLabel10 = new javax.swing.JLabel();
        TXTTele1 = new controls.JTextBox(180);
        jLabel11 = new javax.swing.JLabel();
        TXTOffer1 = new controls.JTextBox(180);
        jLabel12 = new javax.swing.JLabel();
        TXTChair1 = new controls.JTextBox(180);
        jLabel13 = new javax.swing.JLabel();
        TXTPSSN2 = new controls.JTextBox(180);
        BTNAdd1 = new controls.JMybotton();
        BTNPrint1 = new controls.JMybotton();
        LBLCover = new javax.swing.JLabel();
        BTNUpload = new controls.JMybotton();
        BTNSeate2 = new controls.JMybotton();
        LBLImage1 = new javax.swing.JLabel();
        External = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ExternalAdd = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        TXTName2 = new controls.JTextBox(180);
        jLabel15 = new javax.swing.JLabel();
        TXTPassport2 = new controls.JTextBox(180);
        jLabel16 = new javax.swing.JLabel();
        TXTTele2 = new controls.JTextBox(180);
        jLabel17 = new javax.swing.JLabel();
        TXTOffer2 = new controls.JTextBox(180);
        jLabel18 = new javax.swing.JLabel();
        TXTChair2 = new controls.JTextBox(180);
        jLabel19 = new javax.swing.JLabel();
        TXTParent2 = new controls.JTextBox(180);
        BTNAdd2 = new controls.JMybotton();
        BTNPrint2 = new controls.JMybotton();
        LBLIco2 = new javax.swing.JLabel();
        BTNUpload2 = new controls.JMybotton();
        BTNSeate3 = new controls.JMybotton();
        LBLImage2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Internal.setLayout(null);

        jScrollPane1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        InternalAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        InternalAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الأسم", "الرقم القومى", "رقم العرض", "رقم التليفون", "رقم الكرسى", "الرقم القومى للمسئول"
            }
        ));
        jScrollPane1.setViewportView(InternalAdd);

        Internal.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 720, 180);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الأسم");
        Internal.add(jLabel2);
        jLabel2.setBounds(680, 200, 40, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Internal.add(TXTName);
        TXTName.setBounds(500, 200, 180, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الرقم القومى");
        Internal.add(jLabel3);
        jLabel3.setBounds(390, 200, 90, 15);

        TXTSSN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTSSN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSSNActionPerformed(evt);
            }
        });
        Internal.add(TXTSSN);
        TXTSSN.setBounds(210, 200, 180, 19);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم التليفون");
        Internal.add(jLabel4);
        jLabel4.setBounds(660, 240, 80, 15);

        TXTTele.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTeleActionPerformed(evt);
            }
        });
        Internal.add(TXTTele);
        TXTTele.setBounds(480, 240, 180, 19);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("رقم العرض");
        Internal.add(jLabel5);
        jLabel5.setBounds(400, 240, 70, 15);

        TXTCode.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTCode.setEnabled(false);
        TXTCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCodeActionPerformed(evt);
            }
        });
        Internal.add(TXTCode);
        TXTCode.setBounds(210, 240, 180, 19);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("رقم الكرسى");
        Internal.add(jLabel6);
        jLabel6.setBounds(660, 270, 80, 15);

        TXTChair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTChair.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTChair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTChairActionPerformed(evt);
            }
        });
        Internal.add(TXTChair);
        TXTChair.setBounds(480, 270, 180, 19);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("رقم المسئول");
        Internal.add(jLabel7);
        jLabel7.setBounds(390, 270, 80, 15);

        TXTParent.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTParent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTParent.setEnabled(false);
        TXTParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTParentActionPerformed(evt);
            }
        });
        Internal.add(TXTParent);
        TXTParent.setBounds(210, 270, 180, 19);

        BTNSeate1.setText("اختر كرسى");
        BTNSeate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeate1ActionPerformed(evt);
            }
        });
        Internal.add(BTNSeate1);
        BTNSeate1.setBounds(200, 310, 140, 25);

        BTNAdd.setText("أضف المرافقين");
        BTNAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddActionPerformed(evt);
            }
        });
        Internal.add(BTNAdd);
        BTNAdd.setBounds(530, 310, 140, 25);

        BTNReset1.setText("اعرض الفاتورة");
        BTNReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReset1ActionPerformed(evt);
            }
        });
        Internal.add(BTNReset1);
        BTNReset1.setBounds(370, 310, 140, 25);
        Internal.add(LBLImage);
        LBLImage.setBounds(0, 0, 770, 350);

        Panel.addTab("داخلى", Internal);

        Umrah.setLayout(null);

        jScrollPane2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        UmrahAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الأسم", "رقم الباسبور", "رقم العرض", "رقم التليفون", "رقم الكرسى", "الرقم القومى للمسئول", "الصوره"
            }
        ));
        jScrollPane2.setViewportView(UmrahAdd);

        Umrah.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 750, 180);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("الأسم");
        Umrah.add(jLabel8);
        jLabel8.setBounds(680, 200, 40, 15);

        TXTName1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Umrah.add(TXTName1);
        TXTName1.setBounds(500, 200, 180, 19);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("رقم الباسبور");
        Umrah.add(jLabel9);
        jLabel9.setBounds(390, 200, 90, 15);

        TXTPassport.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTPassport.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPassportActionPerformed(evt);
            }
        });
        Umrah.add(TXTPassport);
        TXTPassport.setBounds(210, 200, 180, 19);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("رقم التليفون");
        Umrah.add(jLabel10);
        jLabel10.setBounds(660, 240, 80, 15);

        TXTTele1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTTele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTele1ActionPerformed(evt);
            }
        });
        Umrah.add(TXTTele1);
        TXTTele1.setBounds(480, 240, 180, 19);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("رقم العرض");
        Umrah.add(jLabel11);
        jLabel11.setBounds(400, 240, 70, 15);

        TXTOffer1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTOffer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTOffer1.setEnabled(false);
        TXTOffer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTOffer1ActionPerformed(evt);
            }
        });
        Umrah.add(TXTOffer1);
        TXTOffer1.setBounds(210, 240, 180, 19);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("رقم الكرسى");
        Umrah.add(jLabel12);
        jLabel12.setBounds(660, 270, 80, 15);

        TXTChair1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTChair1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTChair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTChair1ActionPerformed(evt);
            }
        });
        Umrah.add(TXTChair1);
        TXTChair1.setBounds(480, 270, 180, 19);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("رقم المسئول");
        Umrah.add(jLabel13);
        jLabel13.setBounds(390, 270, 80, 15);

        TXTPSSN2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTPSSN2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTPSSN2.setEnabled(false);
        TXTPSSN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPSSN2ActionPerformed(evt);
            }
        });
        Umrah.add(TXTPSSN2);
        TXTPSSN2.setBounds(210, 270, 180, 19);

        BTNAdd1.setText("أضف المرافقين");
        BTNAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAdd1ActionPerformed(evt);
            }
        });
        Umrah.add(BTNAdd1);
        BTNAdd1.setBounds(560, 310, 140, 25);

        BTNPrint1.setText("أعرض فاتورة");
        BTNPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPrint1ActionPerformed(evt);
            }
        });
        Umrah.add(BTNPrint1);
        BTNPrint1.setBounds(390, 310, 140, 25);

        LBLCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Umrah.add(LBLCover);
        LBLCover.setBounds(30, 200, 120, 100);

        BTNUpload.setText("أرفع صورة");
        BTNUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUploadActionPerformed(evt);
            }
        });
        Umrah.add(BTNUpload);
        BTNUpload.setBounds(20, 310, 140, 25);

        BTNSeate2.setText("اختر كرسى");
        BTNSeate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeate2ActionPerformed(evt);
            }
        });
        Umrah.add(BTNSeate2);
        BTNSeate2.setBounds(230, 310, 140, 25);
        Umrah.add(LBLImage1);
        LBLImage1.setBounds(0, 0, 770, 350);

        Panel.addTab("عمره", Umrah);

        External.setLayout(null);

        jScrollPane3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        ExternalAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الأسم", "رقم الباسبور", "رقم العرض", "رقم التليفون", "رقم الكرسى", "الرقم القومى للمسئول", "الصوره"
            }
        ));
        jScrollPane3.setViewportView(ExternalAdd);

        External.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 750, 180);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("الأسم");
        External.add(jLabel14);
        jLabel14.setBounds(680, 200, 40, 15);

        TXTName2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        External.add(TXTName2);
        TXTName2.setBounds(500, 200, 180, 19);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("رقم الباسبور");
        External.add(jLabel15);
        jLabel15.setBounds(390, 200, 90, 15);

        TXTPassport2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTPassport2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTPassport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPassport2ActionPerformed(evt);
            }
        });
        External.add(TXTPassport2);
        TXTPassport2.setBounds(210, 200, 180, 19);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("رقم التليفون");
        External.add(jLabel16);
        jLabel16.setBounds(660, 240, 80, 15);

        TXTTele2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTTele2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTele2ActionPerformed(evt);
            }
        });
        External.add(TXTTele2);
        TXTTele2.setBounds(480, 240, 180, 19);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("رقم العرض");
        External.add(jLabel17);
        jLabel17.setBounds(400, 240, 70, 15);

        TXTOffer2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTOffer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTOffer2.setEnabled(false);
        TXTOffer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTOffer2ActionPerformed(evt);
            }
        });
        External.add(TXTOffer2);
        TXTOffer2.setBounds(210, 240, 180, 19);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("رقم الكرسى");
        External.add(jLabel18);
        jLabel18.setBounds(660, 270, 80, 15);

        TXTChair2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTChair2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTChair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTChair2ActionPerformed(evt);
            }
        });
        External.add(TXTChair2);
        TXTChair2.setBounds(480, 270, 180, 19);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("رقم المسئول");
        External.add(jLabel19);
        jLabel19.setBounds(390, 270, 80, 15);

        TXTParent2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTParent2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTParent2.setEnabled(false);
        TXTParent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTParent2ActionPerformed(evt);
            }
        });
        External.add(TXTParent2);
        TXTParent2.setBounds(210, 270, 180, 19);

        BTNAdd2.setText("أضف المرافقين");
        BTNAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAdd2ActionPerformed(evt);
            }
        });
        External.add(BTNAdd2);
        BTNAdd2.setBounds(570, 310, 140, 25);

        BTNPrint2.setText("إطبع فاتورة");
        BTNPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPrint2ActionPerformed(evt);
            }
        });
        External.add(BTNPrint2);
        BTNPrint2.setBounds(410, 310, 140, 25);

        LBLIco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        External.add(LBLIco2);
        LBLIco2.setBounds(30, 200, 120, 100);

        BTNUpload2.setText("أرفع صورة");
        BTNUpload2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUpload2ActionPerformed(evt);
            }
        });
        External.add(BTNUpload2);
        BTNUpload2.setBounds(20, 310, 140, 25);

        BTNSeate3.setText("اختر كرسى");
        BTNSeate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeate3ActionPerformed(evt);
            }
        });
        External.add(BTNSeate3);
        BTNSeate3.setBounds(250, 310, 140, 25);
        External.add(LBLImage2);
        LBLImage2.setBounds(0, 0, 770, 350);

        Panel.addTab("خارجى", External);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("صفحة لاضافة المارافقين");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 624, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(Panel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSSNActionPerformed

    private void TXTTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTeleActionPerformed

    private void TXTCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCodeActionPerformed

    private void TXTChairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTChairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTChairActionPerformed

    private void TXTParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTParentActionPerformed

    private void TXTPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPassportActionPerformed

    private void TXTTele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTele1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTele1ActionPerformed

    private void TXTOffer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTOffer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTOffer1ActionPerformed

    private void TXTChair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTChair1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTChair1ActionPerformed

    private void TXTPSSN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPSSN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPSSN2ActionPerformed

    private void TXTPassport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPassport2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPassport2ActionPerformed

    private void TXTTele2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTele2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTele2ActionPerformed

    private void TXTOffer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTOffer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTOffer2ActionPerformed

    private void TXTChair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTChair2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTChair2ActionPerformed

    private void TXTParent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTParent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTParent2ActionPerformed

    // This Add Button for Internal Sektion.
    private void BTNAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddActionPerformed
        if (TXTName.getText().equals("") || TXTSSN.getText().equals("") || TXTChair.getText().equals(""))
        {
            Tools.myMess("من فضلك املئ كل البيانات");
        }
        else
        {
            in.setOffer_code(Integer.parseInt(TXTCode.getText()));
            if (in.count() == 47)
            {
                Tools.myMess("تمت حجز الرحلة بالكامل");
                int x = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                if (x == 0)
                {
                    Tools.openForm(new FlightStatement());
                    this.dispose();
                }
            }
            else
            {
                ac.setName(TXTName.getText());
                ac.setSSN(Long.parseLong(TXTSSN.getText()));
                ac.setTele(TXTTele.getText());
                ac.setOffer_code(Integer.parseInt(TXTCode.getText()));
                ac.setSeate(Integer.parseInt(TXTChair.getText()));
                ac.setPSSN1(Long.parseLong(TXTParent.getText()));

                boolean a = ac.quary();

                if (a == true)
                {
                    Tools.myMess("هذا الكرسى تم حجزه بالفعل");
                    TXTChair.setText("");
                    TXTChair.requestFocus();
                }
                else
                {
                    ac.add();
                    ac.getOneRow(InternalAdd, "Accompanying", 0, 0);
                }
            }
            
        }
    }//GEN-LAST:event_BTNAddActionPerformed

    DefaultTableModel Model;
    
    // set Model For Internal Table.
    private void setModel ()
    {
        Model = (DefaultTableModel) InternalAdd.getModel();
    }
    
    // set Model For Umrah Table.
    private void setModel1 ()
    {
        Model = (DefaultTableModel) UmrahAdd.getModel();
    }
    
    // set Model For External Table.
    private void setModel2 ()
    {
        Model = (DefaultTableModel) ExternalAdd.getModel();
    }
    
    // This Print Resete Button for Internal Sektion.
    private void BTNSeate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeate1ActionPerformed
        Tools.openForm(new SeateNumber1());
    }//GEN-LAST:event_BTNSeate1ActionPerformed

    // This Add Button for Umrah Sektion.
    private void BTNAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAdd1ActionPerformed
        if (TXTName1.getText().equals("") || TXTPassport.getText().equals("") || TXTTele1.getText().equals("")
                || TXTChair1.getText().equals("") || URL == null)
        {
            Tools.myMess("املئ كل البيانات من فضلك");
        }
        else
        {
            if (TXTPassport.getText().length() != 9)
            {
                Tools.myMess("اكتب رقم الباسبور الصالح");
                TXTPassport.setText("");
                TXTPassport.requestFocus();
            }
            else
            {
                u.setOffer_code(Integer.parseInt(TXTOffer1.getText()));
                if (u.count() == 47)
                {
                    Tools.myMess("تمت حجز الرحلة بالكامل");
                    int x = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                    if (x == 0)
                    {
                        Tools.openForm(new FlightStatement());
                        this.dispose();
                    }
                }
                else
                {
                    ac.setName(TXTName1.getText());
                    ac.setPSSN(TXTPassport.getText());
                    ac.setTele(TXTTele1.getText());
                    ac.setOffer_code(Integer.parseInt(TXTOffer1.getText()));
                    ac.setSeate(Integer.parseInt(TXTChair1.getText()));
                    ac.setPASSN2(TXTPSSN2.getText());
                    URL = URL.replace("\\", "\\\\");
                    ac.setPhoto(URL);
                    if (u.quary() == true)
                    {
                        Tools.myMess("هذا الكرسى تم حجزه بالفعل");
                        TXTChair1.setText("");
                        TXTChair1.requestFocus();
                    }
                    else
                    {
                        setModel1();
                        ac.add1();
                        ac.getOneRowU(UmrahAdd, "Umrah_Reservarion", 0, 0);
                    }
                }
                
            }
        }
    }//GEN-LAST:event_BTNAdd1ActionPerformed

    // This Print Resete Button for Umrah Sektion.
    private void BTNPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPrint1ActionPerformed
        u.setOffer_code(Integer.parseInt(TXTOffer1.getText()));
        int price = Integer.parseInt(u.Quary());
        int count = Integer.parseInt(ac.countU()) + 1;
        
        // get the final cash in gui form.
        UmrahSektion.TXTCash.setText(String.valueOf(price*count));
        
        String path = null;
        JFileChooser ch = new JFileChooser();
        ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int y = ch.showSaveDialog(this);
        if (y == JFileChooser.APPROVE_OPTION)
        {
            path = ch.getSelectedFile().toString();
        }
        try {
            setModel1();
            PrintWriter ws = new PrintWriter(path+".txt");
            ws.println(" ---------------- The final coast you will cash it -------------------- ");
            ws.println("Person number 1  : "+UmrahSektion.TXTName.getText() + "    " +" his price "+price);
            for (int i=0 ; i< Model.getRowCount() ; i++)
            {
                ws.println("Person number "+ i+2 +" : "+ Model.getValueAt(i, 0) + "    " +" his price "+price);
            }
            ws.println("-------------------------------------------------------------------------");
            // get the final cash in resete text.
            ws.println(" The Result is "+ Integer.parseInt(UmrahSektion.TXTCash.getText()));
            ws.println(" The Resete was written by "+in.getEmp_name() + " and");
            ws.println(" It was printed in "+Tools.PrintDate());
            ws.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InternalSektion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BTNPrint1ActionPerformed

    // this for Umarh To Get Photo.
    private void BTNUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUploadActionPerformed
        URL = Tools.GetAnyPhoto(BTNUpload, LBLCover, 120, 100);
    }//GEN-LAST:event_BTNUploadActionPerformed
    
    // this for External To Get Photo.
    private void BTNUpload2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUpload2ActionPerformed
        URL = Tools.GetAnyPhoto(BTNUpload2, LBLIco2, 120, 100);
    }//GEN-LAST:event_BTNUpload2ActionPerformed

    // This Add Button for External Sektion.
    private void BTNAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAdd2ActionPerformed
        if (TXTName2.getText().equals("") || TXTPassport2.getText().equals("") || TXTTele2.getText().equals("")
                || TXTChair2.getText().equals("") || URL == null)
        {
            Tools.myMess("املئ كل البيانات من فضلك");
        }
        else
        {
            if (TXTPassport2.getText().length() != 9)
            {
                Tools.myMess("اكتب رقم الباسبور الصالح");
                TXTPassport2.setText("");
                TXTPassport2.requestFocus();
            }
            else
            {
                ex.setOffer_code(Integer.parseInt(TXTOffer1.getText()));
                if (ex.count() == 47)
                {
                    Tools.myMess("تمت حجز الرحلة بالكامل");
                    int x = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                    if (x == 0)
                    {
                        Tools.openForm(new FlightStatement());
                        this.dispose();
                    }
                }
                else
                {
                    ac.setName(TXTName2.getText());
                    ac.setPSSN(TXTPassport2.getText());
                    ac.setTele(TXTTele2.getText());
                    ac.setOffer_code(Integer.parseInt(TXTOffer2.getText()));
                    ac.setSeate(Integer.parseInt(TXTChair2.getText()));
                    ac.setPASSN3(TXTParent2.getText());
                    URL = URL.replace("\\", "\\\\");
                    ac.setPhoto(URL);

                    if (ac.quaryE() == true)
                    {
                        Tools.myMess("هذا الكرسى تم حجزه بالفعل");
                        TXTChair2.setText("");
                        TXTChair2.requestFocus();
                    }
                    else
                    {
                        setModel2();
                        ac.add2();
                        ac.getOneRowE(ExternalAdd, "External_Reservarion", 0, 0);
                    }
                }   
            }
        }
    }//GEN-LAST:event_BTNAdd2ActionPerformed

    // This Print Resete Button for External Sektion.
    private void BTNPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPrint2ActionPerformed
       ex.setOffer_code(Integer.parseInt(TXTOffer2.getText()));
       int price = Integer.parseInt(ex.Quary());
       int count = Integer.parseInt(ac.countE()) + 1;
       
       // get the final cash in gui form.
       ExternalSektion.TXTCash.setText(String.valueOf(price*count));
       
        String path = null;
        JFileChooser ch = new JFileChooser();
        ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int y = ch.showSaveDialog(this);
        if (y == JFileChooser.APPROVE_OPTION)
        {
            path = ch.getSelectedFile().toString();
        }
        try {
            setModel2();
            PrintWriter ws = new PrintWriter(path+".txt");
            ws.println(" ---------------- The final coast you will cash it -------------------- ");
            ws.println("Person number 1  : "+ExternalSektion.TXTName.getText() + "    " +" his price "+price);
            for (int i=0 ; i< Model.getRowCount() ; i++)
            {
                ws.println("Person number "+ i+2 +" : "+ Model.getValueAt(i, 0) + "    " +" his price "+price);
            }
            ws.println("-------------------------------------------------------------------------");
            // get the final cash in resete text.
            ws.println(" The Result is "+ Integer.parseInt(ExternalSektion.TXTCash.getText()));
            ws.println(" The Resete was written by "+in.getEmp_name() + " and");
            ws.println(" It was printed in "+Tools.PrintDate());
            ws.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InternalSektion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BTNPrint2ActionPerformed

    private void BTNReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReset1ActionPerformed
        in.setOffer_code(Integer.parseInt(TXTCode.getText()));
        int price = Integer.parseInt(in.Quary());
        int count = Integer.parseInt(ac.count()) + 1;
        
        // print the final cash to two method one of theme to the GUI and two to the file Recete
        InternalSektion.TXTFinalCoast.setText(String.valueOf(price*count));
        
        String path = null;
        JFileChooser ch = new JFileChooser();
        ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int y = ch.showSaveDialog(this);
        
        if (y == JFileChooser.APPROVE_OPTION)
        {
            path = ch.getSelectedFile().toString();
        }
        try {
            setModel();
            PrintWriter ws = new PrintWriter(path+".txt");
            ws.println(" ---------------- The final coast you will cash it -------------------- ");
            ws.println("Person number 1  : "+InternalSektion.TXTName.getText() + "    " +" his price "+price);
            for (int i=0 ; i< Model.getRowCount() ; i++)
            {
                ws.println("Person number "+ i+2 +" : "+ Model.getValueAt(i, 0) + "    " +" his price "+price);
            }
            ws.println("-------------------------------------------------------------------------");
            ws.println(" The Result is "+ Integer.parseInt(TXTFinalCoast.getText()));
            ws.println(" The Resete was written by "+in.getEmp_name() + " and");
            ws.println(" It was printed in "+Tools.PrintDate());
            ws.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InternalSektion.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BTNReset1ActionPerformed

    private void BTNSeate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeate2ActionPerformed
        Tools.openForm(new SeateNumber2());
    }//GEN-LAST:event_BTNSeate2ActionPerformed

    private void BTNSeate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeate3ActionPerformed
        Tools.openForm(new SeateNumber3());
    }//GEN-LAST:event_BTNSeate3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccompanyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccompanyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccompanyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccompanyingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccompanyingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNAdd;
    private controls.JMybotton BTNAdd1;
    private controls.JMybotton BTNAdd2;
    private controls.JMybotton BTNPrint1;
    private controls.JMybotton BTNPrint2;
    private controls.JMybotton BTNReset1;
    private controls.JMybotton BTNSeate1;
    private controls.JMybotton BTNSeate2;
    private controls.JMybotton BTNSeate3;
    private controls.JMybotton BTNUpload;
    private controls.JMybotton BTNUpload2;
    private javax.swing.JPanel External;
    private javax.swing.JTable ExternalAdd;
    private javax.swing.JPanel Internal;
    private javax.swing.JTable InternalAdd;
    private javax.swing.JLabel LBLCover;
    private javax.swing.JLabel LBLIco2;
    private javax.swing.JLabel LBLImage;
    private javax.swing.JLabel LBLImage1;
    private javax.swing.JLabel LBLImage2;
    public static javax.swing.JTabbedPane Panel;
    public static javax.swing.JTextField TXTChair;
    public static javax.swing.JTextField TXTChair1;
    public static javax.swing.JTextField TXTChair2;
    public static javax.swing.JTextField TXTCode;
    private javax.swing.JTextField TXTName;
    private javax.swing.JTextField TXTName1;
    private javax.swing.JTextField TXTName2;
    public static javax.swing.JTextField TXTOffer1;
    public static javax.swing.JTextField TXTOffer2;
    public static javax.swing.JTextField TXTPSSN2;
    public static javax.swing.JTextField TXTParent;
    public static javax.swing.JTextField TXTParent2;
    private javax.swing.JTextField TXTPassport;
    private javax.swing.JTextField TXTPassport2;
    private javax.swing.JTextField TXTSSN;
    private javax.swing.JTextField TXTTele;
    private javax.swing.JTextField TXTTele1;
    private javax.swing.JTextField TXTTele2;
    private javax.swing.JPanel Umrah;
    private javax.swing.JTable UmrahAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
