/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author mohamed
 */

import Classes.Itinerary;
import DataBase.Go;
import java.awt.Color;
import java.awt.ComponentOrientation;
import tourism.company.Tools;

public class AddOffer extends javax.swing.JFrame {

    /**
     * Creates new form AddOffer
     */
    public AddOffer() {
        initComponents();
        TXTDetails.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        ComboType.addItem("");
        ComboType.addItem("داخلى");
        ComboType.addItem("عمره");
        ComboType.addItem("خارجى");
        TXTOffer.setDisabledTextColor(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTOffer = new controls.JTextBox(170);
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTDetails = new javax.swing.JTextArea();
        LBLCover = new javax.swing.JLabel();
        BTNCHooce = new controls.JMybotton();
        BTNAdd = new controls.JMybotton();
        jLabel6 = new javax.swing.JLabel();
        TXTCoast = new controls.JTextBox(170);
        jLabel7 = new javax.swing.JLabel();
        TXTID = new controls.JTextBox(170);
        jLabel3 = new javax.swing.JLabel();
        TXTNumber = new controls.JTextBox(170);
        jLabel8 = new javax.swing.JLabel();
        TXTID1 = new controls.JTextBox(170);
        jLabel5 = new javax.swing.JLabel();
        ComboType = new controls.JMyCompo();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuReservation = new javax.swing.JMenu();
        MenuEmployee = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuReservation6 = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuUpdate1 = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 2));
        JPanel.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("اضافة العروض");
        JPanel.add(jLabel1);
        jLabel1.setBounds(430, 10, 90, 15);

        jLabel2.setText("أسم العرض");
        JPanel.add(jLabel2);
        jLabel2.setBounds(440, 140, 68, 20);

        TXTOffer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTOffer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTOfferActionPerformed(evt);
            }
        });
        JPanel.add(TXTOffer);
        TXTOffer.setBounds(260, 140, 170, 30);

        jLabel4.setText("التفاصيل هنا");
        JPanel.add(jLabel4);
        jLabel4.setBounds(230, 310, 80, 15);

        TXTDetails.setColumns(20);
        TXTDetails.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TXTDetails.setRows(5);
        jScrollPane1.setViewportView(TXTDetails);

        JPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 490, 80);

        LBLCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JPanel.add(LBLCover);
        LBLCover.setBounds(20, 20, 150, 130);

        BTNCHooce.setText("أرفع الصورة");
        BTNCHooce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCHooceActionPerformed(evt);
            }
        });
        JPanel.add(BTNCHooce);
        BTNCHooce.setBounds(40, 160, 108, 25);

        BTNAdd.setText("أضف العـــــــــــرض");
        BTNAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddActionPerformed(evt);
            }
        });
        JPanel.add(BTNAdd);
        BTNAdd.setBounds(150, 430, 200, 30);

        jLabel6.setText("السعر للفرد");
        JPanel.add(jLabel6);
        jLabel6.setBounds(430, 270, 80, 15);

        TXTCoast.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTCoast.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTCoast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCoastActionPerformed(evt);
            }
        });
        JPanel.add(TXTCoast);
        TXTCoast.setBounds(260, 260, 170, 30);

        jLabel7.setText("كود المشرف");
        JPanel.add(jLabel7);
        jLabel7.setBounds(430, 190, 80, 15);

        TXTID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDActionPerformed(evt);
            }
        });
        JPanel.add(TXTID);
        TXTID.setBounds(260, 180, 170, 30);

        jLabel3.setText("نوع العرض");
        JPanel.add(jLabel3);
        jLabel3.setBounds(440, 50, 70, 15);

        TXTNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTNumber.setEnabled(false);
        JPanel.add(TXTNumber);
        TXTNumber.setBounds(260, 90, 170, 30);

        jLabel8.setText("كود المشرف التانى");
        JPanel.add(jLabel8);
        jLabel8.setBounds(390, 230, 120, 15);

        TXTID1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTID1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTID1ActionPerformed(evt);
            }
        });
        JPanel.add(TXTID1);
        TXTID1.setBounds(220, 220, 170, 30);

        jLabel5.setText("رقم العرض");
        JPanel.add(jLabel5);
        jLabel5.setBounds(440, 90, 70, 30);

        ComboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTypeActionPerformed(evt);
            }
        });
        JPanel.add(ComboType);
        ComboType.setBounds(260, 50, 170, 24);

        MenuReservation.setText("ملف");

        MenuEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/business-01-512.png"))); // NOI18N
        MenuEmployee.setText("اضافة موظفين");
        MenuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmployeeActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuEmployee);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        jMenuItem4.setText("الحجز");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuReservation.add(jMenuItem4);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuOffer);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuNote);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuCalculator);

        MenuReservation6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation6.setText("رجوع");
        MenuReservation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservation6ActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuReservation6);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuExit);

        jMenuBar1.add(MenuReservation);

        jMenu1.setText("تعديل");

        jMenuItem6.setText("تغير باسورد المدير");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("تغير بيانات موظف");
        jMenu1.add(jMenuItem7);

        MenuUpdate1.setText("تعديل حجز رحلة داخلية");
        MenuUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdate1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuUpdate1);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        jMenu1.add(MenduExternal);

        jMenuItem3.setText("تعديل حجز رحلة خارجية");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTOfferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTOfferActionPerformed

    private void MenuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmployeeActionPerformed
        Tools.openForm(new EmployeeSignUp());
        this.dispose();
    }//GEN-LAST:event_MenuEmployeeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Tools.openForm(new TypeOfCustomers());
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuReservation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservation6ActionPerformed
        Tools.openForm(new AdminCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservation6ActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdate1ActionPerformed
        Tools.openForm(new InternalUpdate());
    }//GEN-LAST:event_MenuUpdate1ActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void TXTCoastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCoastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCoastActionPerformed

    private void TXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDActionPerformed

    private void BTNAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddActionPerformed
       if (TXTNumber.getText().equals("")|| TXTNumber.getText().equals("أدخل نوع العرض") ||TXTOffer.getText().equals("") ||
               TXTCoast.getText().equals("") || TXTID.getText().equals("") ||
               TXTDetails.getText().equals("") || URL == null)
       {
           Tools.myMess("من فضلك املئ كل البيانات");
       }
       else
       {
           if (TXTID1.getText().equals(""))
           {
               String chooce = ComboType.getSelectedItem().toString();
               Itinerary in = new Itinerary();
               in.setSuper_Id(Integer.parseInt(TXTID.getText()));
               in.setTrip_Name(TXTOffer.getText());
               in.setTrip_code(Integer.parseInt(TXTNumber.getText()));
               in.setCoast(Integer.parseInt(TXTCoast.getText()));
               in.setSuper_Id(Integer.parseInt(TXTID.getText()));
               in.setSuper_Id2(0);
               in.setDescrib(TXTDetails.getText());
               in.setTrip_Cover(URL);
               in.add(chooce);
           }
           else
           {
               String chooce = ComboType.getSelectedItem().toString();
               Itinerary in = new Itinerary();
               in.setSuper_Id(Integer.parseInt(TXTID.getText()));
               in.setTrip_Name(TXTOffer.getText());
               in.setTrip_code(Integer.parseInt(TXTNumber.getText()));
               in.setCoast(Integer.parseInt(TXTCoast.getText()));
               in.setSuper_Id(Integer.parseInt(TXTID.getText()));
               in.setSuper_Id2(Integer.parseInt(TXTID1.getText()));
               in.setDescrib(TXTDetails.getText());
               in.setTrip_Cover(URL);

                in.add(chooce);
           }   
       }
    }//GEN-LAST:event_BTNAddActionPerformed

    private String URL;
    
    private void BTNCHooceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCHooceActionPerformed
        URL = Tools.GetAnyPhoto(BTNCHooce, LBLCover, 150, 130);
    }//GEN-LAST:event_BTNCHooceActionPerformed

    private void TXTID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTID1ActionPerformed

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed
        Itinerary in = new Itinerary();
        TXTNumber.setText(String.valueOf(in.getAutoCodeTrip(ComboType)));
    }//GEN-LAST:event_ComboTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNAdd;
    private controls.JMybotton BTNCHooce;
    private controls.JMyCompo ComboType;
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel LBLCover;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuEmployee;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenu MenuReservation;
    private javax.swing.JMenuItem MenuReservation6;
    private javax.swing.JMenuItem MenuUpdate1;
    private javax.swing.JTextField TXTCoast;
    private javax.swing.JTextArea TXTDetails;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTID1;
    private javax.swing.JTextField TXTNumber;
    private javax.swing.JTextField TXTOffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
