/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import tourism.company.Tools;
import Classes.Admin;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class AdminSignUp extends javax.swing.JFrame {

    /**
     * Creates new form AdminSignUp
     */
    public AdminSignUp() {
        initComponents();
        LBLMess.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(146);
        TXTUser = new controls.JTextBox(146);
        TXTTele = new controls.JTextBox(146);
        ShowPass1 = new javax.swing.JCheckBox();
        ShowPass2 = new javax.swing.JCheckBox();
        TXTPass = new controls.JPasswordBox(146);
        BTNCancel = new controls.JMybotton();
        BTNLogin = new controls.JMybotton();
        jLabel6 = new javax.swing.JLabel();
        TXTConfirm = new controls.JPasswordBox(146);
        LBLMess = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MenuBack = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        jLabel2.setText("الاسم كاملا");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 20, 66, 15);

        jLabel3.setText("اسم المستخدم");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(361, 58, 88, 15);

        jLabel4.setText("كلمة المرور");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 95, 69, 15);

        jLabel5.setText("رقم التليفون");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 190, 79, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTName);
        TXTName.setBounds(203, 13, 146, 19);

        TXTUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTUser);
        TXTUser.setBounds(203, 56, 146, 19);

        TXTTele.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTTele);
        TXTTele.setBounds(190, 190, 146, 19);

        ShowPass1.setText("SP");
        ShowPass1.setOpaque(false);
        ShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPass1ActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass1);
        ShowPass1.setBounds(200, 97, 50, 23);

        ShowPass2.setText("SP");
        ShowPass2.setOpaque(false);
        ShowPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPass2ActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass2);
        ShowPass2.setBounds(190, 150, 50, 30);

        TXTPass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTPass);
        TXTPass.setBounds(199, 93, 150, 30);

        BTNCancel.setText("إلغاء الأمر");
        BTNCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCancel);
        BTNCancel.setBounds(20, 140, 126, 51);

        BTNLogin.setText("تسجيل البيانات");
        BTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BTNLogin);
        BTNLogin.setBounds(20, 70, 126, 51);

        jLabel6.setText("تأكيد كلمة المرور");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 150, 110, 30);

        TXTConfirm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTConfirm);
        TXTConfirm.setBounds(190, 150, 146, 30);

        LBLMess.setForeground(new java.awt.Color(204, 0, 51));
        LBLMess.setText("كلمة المرور غير متطابقة");
        jPanel1.add(LBLMess);
        LBLMess.setBounds(230, 130, 150, 15);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("تسجيل بيانات المدير الأساسية");

        jMenu3.setText("ملف");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        MenuBack.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuBack.setText("رجوع");
        MenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBackActionPerformed(evt);
            }
        });
        jMenu3.add(MenuBack);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu3.add(MenuExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBackActionPerformed
        Tools.openForm(new MainForm());
        this.dispose();
    }//GEN-LAST:event_MenuBackActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        String Name = TXTName.getText();
        String UserName = TXTUser.getText();
        String PassWord = TXTPass.getText();
        String Tele = TXTTele.getText().trim();
        
        if (TXTName.getText().equals("") || TXTUser.getText().equals("") || TXTPass.getText().equals("") || TXTTele.getText().equals(""))
        {
            Tools.myMess("أرجوك املئ كل البيانات");
        }
        else
        {
            try {
                Integer.parseInt(Tele);
            } catch(NumberFormatException ex)
            {
                Tools.myMess("اكتب رقم التليفون صالح");
            }
            
            if (Tele.length() != 11)
            {
                Tools.myMess("اكتب رقم التليفون المكون من احدى عشر رقم");
            }
            else
            {
                if (!TXTPass.getText().equals(TXTConfirm.getText()))
                {
                    LBLMess.setVisible(true);
                    TXTPass.setText("");
                    TXTConfirm.setText("");
                    TXTPass.requestFocus();
                }
                else
                {
                    Admin a = new Admin();
                    a.setName(Name);
                    a.setUserName(UserName);
                    a.setPassWord(PassWord);
                    a.setTele(Tele);

                    a.add();
                }    
            }
        }
        
    }//GEN-LAST:event_BTNLoginActionPerformed

    private void BTNCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "هل تريد الغاء الأمر؟", "الغاء الأمر", JOptionPane.YES_NO_OPTION);
        if (x == 0)
        {
            TXTName.setText("");
            TXTUser.setText("");
            TXTPass.setText("");
            TXTTele.setText("");
            TXTConfirm.setText("");

            TXTName.requestFocus();
        }
    }//GEN-LAST:event_BTNCancelActionPerformed

    private void ShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPass1ActionPerformed
        if (ShowPass1.isSelected())
        {
            TXTPass.setEchoChar((char)0);
        }
        else
        {
            TXTPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ShowPass1ActionPerformed

    private void ShowPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPass2ActionPerformed
        if (ShowPass2.isSelected())
        {
            TXTConfirm.setEchoChar((char)0);
        }
        else
        {
            TXTConfirm.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ShowPass2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNCancel;
    private controls.JMybotton BTNLogin;
    private javax.swing.JLabel LBLMess;
    private javax.swing.JMenuItem MenuBack;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JCheckBox ShowPass1;
    private javax.swing.JCheckBox ShowPass2;
    private javax.swing.JPasswordField TXTConfirm;
    private javax.swing.JTextField TXTName;
    private javax.swing.JPasswordField TXTPass;
    private javax.swing.JTextField TXTTele;
    private javax.swing.JTextField TXTUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
