/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */

public class AdminCataloge extends javax.swing.JFrame {
    public AdminCataloge() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLBackGround, 610, 320);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTNSignout = new controls.JMybotton();
        LBLName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panal = new javax.swing.JPanel();
        BTNSalary = new controls.JMybotton();
        BTNGard = new controls.JMybotton();
        jMybotton3 = new controls.JMybotton();
        BTNDetectName = new controls.JMybotton();
        LBLBackGround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuReservation = new javax.swing.JMenu();
        MenuEmployee = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuSeate = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuChangePass = new javax.swing.JMenuItem();
        MenuEditOffer = new javax.swing.JMenuItem();
        MenuEditEmployee = new javax.swing.JMenuItem();
        MenuUpdate1 = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("مرحباً يا مدير");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 0, 80, 30);

        BTNSignout.setText("تسجيل الخروج");
        BTNSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSignoutActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSignout);
        BTNSignout.setBounds(20, 0, 130, 30);

        LBLName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(LBLName);
        LBLName.setBounds(160, 0, 90, 30);

        jLabel1.setText("اقسام البرنامج المخصصة لمدير الشركة");

        Panal.setLayout(null);

        BTNSalary.setText("المرتبات");
        BTNSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalaryActionPerformed(evt);
            }
        });
        Panal.add(BTNSalary);
        BTNSalary.setBounds(20, 160, 140, 40);

        BTNGard.setText("الجرد");
        BTNGard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGardActionPerformed(evt);
            }
        });
        Panal.add(BTNGard);
        BTNGard.setBounds(490, 80, 100, 40);

        jMybotton3.setText("اضافة العروض");
        jMybotton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybotton3ActionPerformed(evt);
            }
        });
        Panal.add(jMybotton3);
        jMybotton3.setBounds(30, 80, 120, 40);

        BTNDetectName.setText("كشوفات الرحلات");
        BTNDetectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDetectNameActionPerformed(evt);
            }
        });
        Panal.add(BTNDetectName);
        BTNDetectName.setBounds(450, 160, 140, 40);

        LBLBackGround.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        LBLBackGround.setOpaque(true);
        Panal.add(LBLBackGround);
        LBLBackGround.setBounds(0, 0, 610, 320);

        MenuReservation.setText("ملف");

        MenuEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/business-01-512.png"))); // NOI18N
        MenuEmployee.setText("اضافة موظفين");
        MenuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmployeeActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuEmployee);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        jMenuItem4.setText("الحجز");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuReservation.add(jMenuItem4);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuOffer);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        jMenuItem5.setText("الكراسى المتاحه والشاغره");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuReservation.add(jMenuItem5);

        MenuSeate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuSeate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        MenuSeate.setText("عدد الكراسى المتاحه");
        MenuSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSeateActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuSeate);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuNote);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuCalculator);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuExit);

        jMenuBar1.add(MenuReservation);

        jMenu1.setText("تعديل");

        MenuChangePass.setText("تغير باسورد المدير");
        MenuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(MenuChangePass);

        MenuEditOffer.setText("تعديل العروض");
        MenuEditOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditOfferActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEditOffer);

        MenuEditEmployee.setText("تغير بيانات موظف");
        MenuEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEditEmployee);

        MenuUpdate1.setText("تعديل حجز رحلة داخلية");
        MenuUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdate1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuUpdate1);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        jMenu1.add(MenduExternal);

        jMenuItem3.setText("تعديل حجز رحلة خارجية");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(Panal, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panal, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmployeeActionPerformed
        Tools.openForm(new EmployeeSignUp());
    }//GEN-LAST:event_MenuEmployeeActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       Tools.openForm(new TypeOfCustomers());
       this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdate1ActionPerformed
        Tools.openForm(new InternalUpdate());

    }//GEN-LAST:event_MenuUpdate1ActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void BTNDetectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDetectNameActionPerformed
        Tools.openForm(new FlightStatement());
        this.dispose();
    }//GEN-LAST:event_BTNDetectNameActionPerformed

    private void BTNGardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGardActionPerformed
        Tools.openForm(new Gard());
        this.dispose();
    }//GEN-LAST:event_BTNGardActionPerformed

    private void BTNSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalaryActionPerformed
        Tools.openForm(new Salary());
        this.dispose();
    }//GEN-LAST:event_BTNSalaryActionPerformed

    private void jMybotton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybotton3ActionPerformed
        Tools.openForm(new AddOffer());
        this.dispose();
    }//GEN-LAST:event_jMybotton3ActionPerformed

    private void MenuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChangePassActionPerformed
        Tools.openForm(new EditPassAdmin());
    }//GEN-LAST:event_MenuChangePassActionPerformed

    private void MenuEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditEmployeeActionPerformed
        Tools.openForm(new EmployeeUpdate());
    }//GEN-LAST:event_MenuEditEmployeeActionPerformed

    private void MenuEditOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditOfferActionPerformed
        Tools.openForm(new EditOffer());
        this.dispose();
    }//GEN-LAST:event_MenuEditOfferActionPerformed

    private void MenuSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSeateActionPerformed
        Tools.openForm(new SeateAvailbale());
    }//GEN-LAST:event_MenuSeateActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Tools.openForm(new SeateNumber());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BTNSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSignoutActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "هل تريد تسجيل الخروج؟","تأكيد",JOptionPane.YES_NO_OPTION);
        if (x == 0)
        {
            Tools.openForm(new MainForm());
            this.dispose();
        }
    }//GEN-LAST:event_BTNSignoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCataloge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNDetectName;
    private controls.JMybotton BTNGard;
    private controls.JMybotton BTNSalary;
    private controls.JMybotton BTNSignout;
    private javax.swing.JLabel LBLBackGround;
    public static javax.swing.JLabel LBLName;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuChangePass;
    private javax.swing.JMenuItem MenuEditEmployee;
    private javax.swing.JMenuItem MenuEditOffer;
    private javax.swing.JMenuItem MenuEmployee;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenu MenuReservation;
    private javax.swing.JMenuItem MenuSeate;
    private javax.swing.JMenuItem MenuUpdate1;
    private javax.swing.JPanel Panal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private controls.JMybotton jMybotton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
