/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    private double x1;
    private double x2;
    private double res;
    private char ope;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNPlus = new controls.JMybotton1();
        BTNminus = new controls.JMybotton1();
        BTNMulti = new controls.JMybotton1();
        BTNRes = new controls.JMybotton1();
        BTN4 = new controls.JMybotton1();
        BTN8 = new controls.JMybotton1();
        BTN9 = new controls.JMybotton1();
        BTN7 = new controls.JMybotton1();
        BTN5 = new controls.JMybotton1();
        BTN6 = new controls.JMybotton1();
        BTN1 = new controls.JMybotton1();
        BTN2 = new controls.JMybotton1();
        BTN3 = new controls.JMybotton1();
        BTNPN = new controls.JMybotton1();
        BTN0 = new controls.JMybotton1();
        BTNDot = new controls.JMybotton1();
        BTNDiv = new controls.JMybotton1();
        jMybotton28 = new controls.JMybotton1();
        BTNClear = new controls.JMybotton1();
        BTNReset = new controls.JMybotton1();
        jMybotton31 = new controls.JMybotton1();
        BTNPower = new controls.JMybotton1();
        TXTRes = new javax.swing.JTextField();
        BTNExit = new controls.JMybotton1();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTNPlus.setText("+");
        BTNPlus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPlusActionPerformed(evt);
            }
        });

        BTNminus.setText("-");
        BTNminus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNminusActionPerformed(evt);
            }
        });

        BTNMulti.setText("X");
        BTNMulti.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMultiActionPerformed(evt);
            }
        });

        BTNRes.setText("=");
        BTNRes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResActionPerformed(evt);
            }
        });
        BTNRes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTNResKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BTNResKeyReleased(evt);
            }
        });

        BTN4.setText("4");
        BTN4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN4ActionPerformed(evt);
            }
        });

        BTN8.setText("8");
        BTN8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN8ActionPerformed(evt);
            }
        });

        BTN9.setText("9");
        BTN9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN9ActionPerformed(evt);
            }
        });

        BTN7.setText("7");
        BTN7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN7ActionPerformed(evt);
            }
        });

        BTN5.setText("5");
        BTN5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN5ActionPerformed(evt);
            }
        });

        BTN6.setText("6");
        BTN6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN6ActionPerformed(evt);
            }
        });

        BTN1.setText("1");
        BTN1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN1ActionPerformed(evt);
            }
        });

        BTN2.setText("2");
        BTN2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2ActionPerformed(evt);
            }
        });

        BTN3.setText("3");
        BTN3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN3ActionPerformed(evt);
            }
        });

        BTNPN.setText("+/-");
        BTNPN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPNActionPerformed(evt);
            }
        });

        BTN0.setText("0");
        BTN0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN0ActionPerformed(evt);
            }
        });

        BTNDot.setText(".");
        BTNDot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDotActionPerformed(evt);
            }
        });

        BTNDiv.setText("/");
        BTNDiv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDivActionPerformed(evt);
            }
        });

        jMybotton28.setText("del");
        jMybotton28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        BTNClear.setForeground(new java.awt.Color(255, 0, 0));
        BTNClear.setText("C");
        BTNClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClearActionPerformed(evt);
            }
        });

        BTNReset.setForeground(new java.awt.Color(255, 0, 0));
        BTNReset.setText("CE");
        BTNReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        jMybotton31.setText("%");
        jMybotton31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMybotton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybotton31ActionPerformed(evt);
            }
        });

        BTNPower.setText("X^Y");
        BTNPower.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPowerActionPerformed(evt);
            }
        });

        TXTRes.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TXTRes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTRes.setText("0.0");
        TXTRes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTResKeyPressed(evt);
            }
        });

        BTNExit.setForeground(new java.awt.Color(204, 0, 0));
        BTNExit.setText("OFF");
        BTNExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNPN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNDot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNRes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jMybotton31, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BTN7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jMybotton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNminus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(BTNPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(BTNExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(TXTRes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(TXTRes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMybotton31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNPower, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMybotton28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNminus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNPN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNRes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTNExitActionPerformed

    private void BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN1ActionPerformed
        String ss = TXTRes.getText() + "1";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN1ActionPerformed

    private void BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2ActionPerformed
        String ss = TXTRes.getText() + "2";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN2ActionPerformed

    private void BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN3ActionPerformed
        String ss = TXTRes.getText() + "3";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN3ActionPerformed

    private void BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN4ActionPerformed
        String ss = TXTRes.getText() + "4";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN4ActionPerformed

    private void BTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN5ActionPerformed
        String ss = TXTRes.getText() + "5";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN5ActionPerformed

    private void BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN6ActionPerformed
        String ss = TXTRes.getText() + "6";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN6ActionPerformed

    private void BTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN7ActionPerformed
        String ss = TXTRes.getText() + "7";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN7ActionPerformed

    private void BTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN8ActionPerformed
        String ss = TXTRes.getText() + "8";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN8ActionPerformed

    private void BTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN9ActionPerformed
        String ss = TXTRes.getText() + "9";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN9ActionPerformed

    private void BTNDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDotActionPerformed
        String ss = TXTRes.getText() + ".";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTNDotActionPerformed

    private void BTNClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClearActionPerformed
        TXTRes.setText("");
        TXTRes.requestFocus();
    }//GEN-LAST:event_BTNClearActionPerformed

    private void setOpe(char ope)
    {
        x1 = Double.parseDouble(TXTRes.getText());
        TXTRes.setText("");
        TXTRes.requestFocus();
        this.ope = ope;
    }
        
    private void BTNPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPlusActionPerformed
        setOpe('+');
    }//GEN-LAST:event_BTNPlusActionPerformed

    private void BTNResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResActionPerformed
        switch (ope)
        {
            case '+':
            {
                x2 = Double.parseDouble(TXTRes.getText());
                TXTRes.setText(String.valueOf(x1+x2));
            }
            break;
            case '-':
            {
                x2 = Double.parseDouble(TXTRes.getText());
                TXTRes.setText(String.valueOf(x1-x2));
            }
            break;
            case '*':
            {
                x2 = Double.parseDouble(TXTRes.getText());
                TXTRes.setText(String.valueOf(x1*x2));
            }
            break;
            case '/':
            {
                x2 = Double.parseDouble(TXTRes.getText());
                if (x2 == 0)
                    Tools.myMess("لا يمكنك القسيمه على صفر");
                else
                    TXTRes.setText(String.valueOf(x1/x2));
            }
            break;
            case '%':
            {
                x2 = Double.parseDouble(TXTRes.getText());
                TXTRes.setText(String.valueOf(x1%x2));
            }
            break;
            case '^':
            {
                double Res = 1;
                for (int i=1 ; i<= Integer.valueOf(TXTRes.getText()) ; i++)
                {
                    Res *= x1;
                }
                TXTRes.setText(String.valueOf(Res));
            }
            break;
        }
    }//GEN-LAST:event_BTNResActionPerformed

    private void BTNminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNminusActionPerformed
        setOpe('-');
    }//GEN-LAST:event_BTNminusActionPerformed

    private void BTNMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMultiActionPerformed
        setOpe('*');
    }//GEN-LAST:event_BTNMultiActionPerformed

    private void BTNDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDivActionPerformed
        setOpe('/');
    }//GEN-LAST:event_BTNDivActionPerformed

    private void BTN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN0ActionPerformed
        String ss = TXTRes.getText() + "0";
        TXTRes.setText(ss);
    }//GEN-LAST:event_BTN0ActionPerformed

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        TXTRes.setText("");
        TXTRes.requestFocus();
        x1 = 0;
        x2 = 0;
        ope = 0;
    }//GEN-LAST:event_BTNResetActionPerformed

    private void BTNPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPNActionPerformed
        TXTRes.setText(String.valueOf(-1 * Double.parseDouble(TXTRes.getText())));
    }//GEN-LAST:event_BTNPNActionPerformed

    private void jMybotton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybotton31ActionPerformed
        setOpe('%');
    }//GEN-LAST:event_jMybotton31ActionPerformed

    private void BTNPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPowerActionPerformed
        setOpe('^');
    }//GEN-LAST:event_BTNPowerActionPerformed

    private void BTNResKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTNResKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNResKeyReleased

    private void BTNResKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTNResKeyPressed
        
    }//GEN-LAST:event_BTNResKeyPressed

    private void TXTResKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTResKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
           switch (ope)
            {
                case '+':
                {
                    x2 = Double.parseDouble(TXTRes.getText());
                    TXTRes.setText(String.valueOf(x1+x2));
                }
                break;
                case '-':
                {
                    x2 = Double.parseDouble(TXTRes.getText());
                    TXTRes.setText(String.valueOf(x1-x2));
                }
                break;
                case '*':
                {
                    x2 = Double.parseDouble(TXTRes.getText());
                    TXTRes.setText(String.valueOf(x1*x2));
                }
                break;
                case '/':
                {
                    x2 = Double.parseDouble(TXTRes.getText());
                    if (x2 == 0)
                        Tools.myMess("لا يمكنك القسمه على صفر");
                    else
                        TXTRes.setText(String.valueOf(x1/x2));
                }
                break;
                case '%':
                {
                    x2 = Double.parseDouble(TXTRes.getText());
                    TXTRes.setText(String.valueOf(x1%x2));
                }
                break;
                case '^':
                {
                    double Res = 1;
                    for (int i=1 ; i<= Integer.valueOf(TXTRes.getText()) ; i++)
                    {
                        Res *= x1;
                    }
                    TXTRes.setText(String.valueOf(Res));
                }
                break;
            }
       }
       
       switch (evt.getKeyCode())
       {
           case KeyEvent.VK_ADD :
           {
                setOpe('+');
           }
           break;
           case KeyEvent.VK_MINUS:
           {
               setOpe('-');
           }
           break;
           case KeyEvent.VK_MULTIPLY:
           {
               setOpe('*');
           }
           break;
           case KeyEvent.VK_DIVIDE:
           {
               setOpe('/');
               TXTRes.setText(null);
           }
           break;
       }
    }//GEN-LAST:event_TXTResKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton1 BTN0;
    private controls.JMybotton1 BTN1;
    private controls.JMybotton1 BTN2;
    private controls.JMybotton1 BTN3;
    private controls.JMybotton1 BTN4;
    private controls.JMybotton1 BTN5;
    private controls.JMybotton1 BTN6;
    private controls.JMybotton1 BTN7;
    private controls.JMybotton1 BTN8;
    private controls.JMybotton1 BTN9;
    private controls.JMybotton1 BTNClear;
    private controls.JMybotton1 BTNDiv;
    private controls.JMybotton1 BTNDot;
    private controls.JMybotton1 BTNExit;
    private controls.JMybotton1 BTNMulti;
    private controls.JMybotton1 BTNPN;
    private controls.JMybotton1 BTNPlus;
    private controls.JMybotton1 BTNPower;
    private controls.JMybotton1 BTNRes;
    private controls.JMybotton1 BTNReset;
    private controls.JMybotton1 BTNminus;
    private javax.swing.JTextField TXTRes;
    private controls.JMybotton1 jMybotton28;
    private controls.JMybotton1 jMybotton31;
    // End of variables declaration//GEN-END:variables
}
