/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Itinerary;
import DataBase.Go;
import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class EditOffer extends javax.swing.JFrame {

    /**
     * Creates new form EditOffer
     */
    Itinerary in = new Itinerary();
    public EditOffer() {
        initComponents();
        TXTDetails.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        ComType.addItem("");
        ComType.addItem("داخلى");
        ComType.addItem("عمره");
        ComType.addItem("خارجى");
        
    }
    
    DefaultTableModel Model;
    
    private void setModel ()
    {
        Model = (DefaultTableModel) InterTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InterTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(140);
        TXTCoast = new controls.JTextBox(140);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCode = new controls.JTextBox(140);
        BTNCancel = new controls.JMybotton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTDetails = new javax.swing.JTextArea();
        BTNEdit = new controls.JMybotton();
        BTNDelete = new controls.JMybotton();
        jLabel6 = new javax.swing.JLabel();
        ComType = new controls.JMyCompo();
        BTNShow = new controls.JMybotton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuReservation = new javax.swing.JMenu();
        MenuEmployee = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuReservation6 = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuChangePass = new javax.swing.JMenuItem();
        MenuEditOffer = new javax.swing.JMenuItem();
        MenuEditEmployee = new javax.swing.JMenuItem();
        MenuUpdate1 = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        InterTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        InterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "كود الرحلة", "الرحلة", "تكلفة الرحلة للفرد", "تفاصيل الرحلة", "كود المشرف", "اسم المشرف", "رقم التليفون"
            }
        ));
        InterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InterTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(InterTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 80, 660, 220);

        jLabel1.setText("تعديل تفاصيل الرحلة");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(690, 10, 130, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الرحلة");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(780, 80, 40, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(TXTName);
        TXTName.setBounds(690, 100, 140, 19);

        TXTCoast.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(TXTCoast);
        TXTCoast.setBounds(690, 180, 140, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("السعر للفرد");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(760, 150, 71, 15);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("التفاصيل");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(760, 330, 60, 40);

        TXTCode.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(TXTCode);
        TXTCode.setBounds(690, 240, 140, 19);

        BTNCancel.setText("الغاء الأمر");
        jPanel1.add(BTNCancel);
        BTNCancel.setBounds(10, 330, 114, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("كود المشرف");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(750, 210, 75, 15);

        TXTDetails.setColumns(20);
        TXTDetails.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTDetails.setRows(5);
        jScrollPane1.setViewportView(TXTDetails);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 310, 380, 90);

        BTNEdit.setText("تعديل العرض");
        BTNEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditActionPerformed(evt);
            }
        });
        jPanel1.add(BTNEdit);
        BTNEdit.setBounds(250, 330, 114, 40);

        BTNDelete.setText("حذف العرض");
        BTNDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(BTNDelete);
        BTNDelete.setBounds(130, 330, 114, 40);

        jLabel6.setText("ادخل نوع الرحلة");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 40, 100, 20);
        jPanel1.add(ComType);
        ComType.setBounds(312, 40, 250, 24);

        BTNShow.setText("اعرض كل العروض للتعديل");
        BTNShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNShowActionPerformed(evt);
            }
        });
        jPanel1.add(BTNShow);
        BTNShow.setBounds(94, 40, 200, 25);

        MenuReservation.setText("ملف");

        MenuEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/business-01-512.png"))); // NOI18N
        MenuEmployee.setText("اضافة موظفين");
        MenuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmployeeActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuEmployee);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        jMenuItem4.setText("الحجز");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuReservation.add(jMenuItem4);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuOffer);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuNote);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuCalculator);

        MenuReservation6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation6.setText("رجوع");
        MenuReservation6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservation6ActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuReservation6);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuExit);

        jMenuBar1.add(MenuReservation);

        jMenu1.setText("تعديل ");

        MenuChangePass.setText("تغير باسورد المدير");
        MenuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(MenuChangePass);

        MenuEditOffer.setText("تعديل العروض");
        jMenu1.add(MenuEditOffer);

        MenuEditEmployee.setText("تغير بيانات موظف");
        MenuEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEditEmployee);

        MenuUpdate1.setText("تعديل حجز رحلة داخلية");
        MenuUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdate1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuUpdate1);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        jMenu1.add(MenduExternal);

        jMenuItem3.setText("تعديل حجز رحلة خارجية");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmployeeActionPerformed
        Tools.openForm(new EmployeeSignUp());
    }//GEN-LAST:event_MenuEmployeeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Tools.openForm(new TypeOfCustomers());
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChangePassActionPerformed
        Tools.openForm(new EditPassAdmin());
    }//GEN-LAST:event_MenuChangePassActionPerformed

    private void MenuEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditEmployeeActionPerformed
        Tools.openForm(new EmployeeUpdate());
    }//GEN-LAST:event_MenuEditEmployeeActionPerformed

    private void MenuUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdate1ActionPerformed
        Tools.openForm(new InternalUpdate());
    }//GEN-LAST:event_MenuUpdate1ActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuReservation6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservation6ActionPerformed
        Tools.openForm(new AdminCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservation6ActionPerformed
    private int i; // to get selected row from table to send it to update it.
    private void InterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InterTableMouseClicked
        //Go.filltotable("EditOffer", InterTable, 0, 6);
        setModel();
        i = InterTable.getSelectedRow();
        TXTName.setText(Model.getValueAt(i, 1).toString());
        TXTCoast.setText(Model.getValueAt(i, 2).toString());
        TXTDetails.setText(Model.getValueAt(i, 3).toString());
        TXTCode.setText(Model.getValueAt(i, 4).toString());
        TXTName.requestFocus();
    }//GEN-LAST:event_InterTableMouseClicked

    private void BTNEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditActionPerformed
        in.setTrip_code(Integer.parseInt(Model.getValueAt(i, 0).toString()));
        in.setTrip_Name(TXTName.getText());
        in.setCoast(Integer.parseInt(TXTCoast.getText()));
        in.setDescrib(TXTDetails.getText());
        in.setSuper_Id(Integer.parseInt(TXTCode.getText()));
        in.setSuper_Id2(Integer.parseInt(Model.getValueAt(i,4).toString()));
        
        in.update(ComType.getSelectedItem().toString());
        
        if (ComType.getSelectedItem().toString().equals("داخلى"))
        {
            Go.filltotable("EditOffer", InterTable, 0, 7);
            TXTName.setText("");
            TXTCoast.setText("");
            TXTDetails.setText("");
            TXTCode.setText("");
            TXTName.requestFocus();
        }
        else if (ComType.getSelectedItem().toString().equals("عمره"))
        {
            Go.filltotable("EditOffer1", InterTable, 0, 7);
            TXTName.setText("");
            TXTCoast.setText("");
            TXTDetails.setText("");
            TXTCode.setText("");
            TXTName.requestFocus();
        }
        else if (ComType.getSelectedItem().toString().equals("خارجى"))
        {
            Go.filltotable("EditOffer2", InterTable, 0, 7);
            TXTName.setText("");
            TXTCoast.setText("");
            TXTDetails.setText("");
            TXTCode.setText("");
            TXTName.requestFocus();
        }
    }//GEN-LAST:event_BTNEditActionPerformed

    private void BTNShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNShowActionPerformed
        String sc = ComType.getSelectedItem().toString();
        if (sc.equals("داخلى"))
        {
            Go.filltotable("EditOffer", InterTable, 0, 7);
        }
        else if (sc.equals("عمره"))
        {
            Go.filltotable("EditOffer1", InterTable, 0, 7);
        }
        else if (sc.equals("خارجى"))
        {
            Go.filltotable("EditOffer2", InterTable, 0, 7);
        }
    }//GEN-LAST:event_BTNShowActionPerformed

    private void BTNDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDeleteActionPerformed
        String CC = ComType.getSelectedItem().toString();
        int x = JOptionPane.showConfirmDialog(null,"هل تريد المسح؟","المسح",JOptionPane.YES_NO_OPTION);
        if (x == 0)
        {
            in.setTrip_code(Integer.parseInt(Model.getValueAt(i, 0).toString()));
            
            in.delete(CC);
            if (CC.equals("داخلى"))
            {
                Go.filltotable("EditOffer", InterTable, 0, 7);
            }
            else if (CC.equals("عمره"))
            {
                Go.filltotable("EditOffer1", InterTable, 0, 7);
            }
            else if (CC.equals("خارجى"))
            {
                Go.filltotable("EditOffer2", InterTable, 0, 7);
            }
            
        }
    }//GEN-LAST:event_BTNDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOffer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNCancel;
    private controls.JMybotton BTNDelete;
    private controls.JMybotton BTNEdit;
    private controls.JMybotton BTNShow;
    private controls.JMyCompo ComType;
    private javax.swing.JTable InterTable;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuChangePass;
    private javax.swing.JMenuItem MenuEditEmployee;
    private javax.swing.JMenuItem MenuEditOffer;
    private javax.swing.JMenuItem MenuEmployee;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenu MenuReservation;
    private javax.swing.JMenuItem MenuReservation6;
    private javax.swing.JMenuItem MenuUpdate1;
    private javax.swing.JTextField TXTCoast;
    private javax.swing.JTextField TXTCode;
    private javax.swing.JTextArea TXTDetails;
    private javax.swing.JTextField TXTName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
