/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Admin;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class EditPassAdmin extends javax.swing.JFrame {

    /**
     * Creates new form EditPassAdmin
     */
    public EditPassAdmin() {
        initComponents();
        Tools.setIcon("src/Photo/ChangePass.png", LBLImage, 130, 120);
        LBLMess.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LBLImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTOld = new controls.JPasswordBox(140);
        TXTNew = new controls.JPasswordBox(140);
        jLabel3 = new javax.swing.JLabel();
        TXTConfirm = new controls.JPasswordBox(140);
        jLabel4 = new javax.swing.JLabel();
        LBLMess = new javax.swing.JLabel();
        jMybotton1 = new controls.JMybotton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        jLabel1.setText("تغير كلمة مرور المدير");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(291, 10, 130, 15);
        jPanel1.add(LBLImage);
        LBLImage.setBounds(20, 40, 130, 120);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("كلمة المرور القديمة");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 50, 130, 15);

        TXTOld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTOld);
        TXTOld.setBounds(159, 50, 140, 19);

        TXTNew.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTNew);
        TXTNew.setBounds(160, 100, 140, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("كلمة المرور الجديدة");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 100, 120, 15);

        TXTConfirm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTConfirm);
        TXTConfirm.setBounds(160, 130, 140, 19);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("تأكيد كلمة المرور");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 130, 110, 15);

        LBLMess.setForeground(new java.awt.Color(255, 0, 0));
        LBLMess.setText("كلمة المرور غير متطابقة");
        jPanel1.add(LBLMess);
        LBLMess.setBounds(230, 80, 160, 15);

        jMybotton1.setText("حفظ التغيرات");
        jMybotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybotton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jMybotton1);
        jMybotton1.setBounds(200, 160, 130, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMybotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybotton1ActionPerformed
        String OldPass = TXTOld.getText();
        String NewPass = TXTNew.getText();
        
        if (TXTOld.getText().equals("") || TXTNew.getText().equals("") || TXTConfirm.getText().equals(""))
        {
            Tools.myMess("ارجوك املئ كل البيانات");
        }
        else
        {
            if (!TXTNew.getText().equals(TXTConfirm.getText()))
            {
                LBLMess.setVisible(true);
                TXTNew.setText("");
                TXTConfirm.setText("");
                TXTNew.requestFocus();
            }
            else
            {
                Admin a = new Admin();
                a.setPassWord(OldPass);
                a.setNew_Pass(NewPass);
                
                a.update();
                TXTOld.setText("");
                TXTNew.setText("");
                TXTConfirm.setText("");
                TXTOld.requestFocus();
            }
        }
    }//GEN-LAST:event_jMybotton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPassAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPassAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPassAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPassAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPassAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLImage;
    private javax.swing.JLabel LBLMess;
    private javax.swing.JPasswordField TXTConfirm;
    private javax.swing.JPasswordField TXTNew;
    private javax.swing.JPasswordField TXTOld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private controls.JMybotton jMybotton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
