/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DataBase.Go;
import javax.swing.JOptionPane;
import tourism.company.Tools;
import Classes.Employee;
import java.awt.Color;

/**
 *
 * @author mohamed
 */
public class EmployeeSignUp extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSingUp
     */
    public EmployeeSignUp() {
        initComponents();
        LBLMess.setVisible(false);
        TXTID.setText(Go.countautonumber("Employee", "id"));
        TXTID.setDisabledTextColor(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TXTID = new controls.JTextBox(110);
        TXTAge = new controls.JTextBox(110);
        TXTSSN = new controls.JTextBox(110);
        TXTTele = new controls.JTextBox(110);
        TXTAdress = new controls.JTextBox(110);
        TXTName = new controls.JTextBox(110);
        TXTSocial = new controls.JTextBox(110);
        TXTSalary = new controls.JTextBox(110);
        TXTJob = new controls.JTextBox(110);
        TXTUser = new controls.JTextBox(110);
        ShowPass = new javax.swing.JCheckBox();
        ShowPass1 = new javax.swing.JCheckBox();
        TXTPass = new controls.JPasswordBox(150);
        jLabel14 = new javax.swing.JLabel();
        TXTConfirm = new controls.JPasswordBox(150);
        LBLImage = new javax.swing.JLabel();
        BTNUpload = new controls.JMybotton();
        BTNCancel = new controls.JMybotton();
        BTNSave = new controls.JMybotton();
        LBLMess = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("العنوات");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 130, 50, 15);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الرقم التسلسلى");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(371, 10, 100, 15);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("الأسم");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 40, 40, 15);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("الرقم القومى");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 70, 90, 15);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("المرتب");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 190, 50, 15);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("رقم التليفون");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 100, 90, 15);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("كلمة السر");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 290, 70, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("الحالة الإجتماعية");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 160, 100, 15);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("الوظيفة ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 220, 60, 15);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("اسم المستخدم");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 260, 90, 15);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("العمر");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 380, 40, 20);

        TXTID.setFont(new java.awt.Font("Ani", 1, 12)); // NOI18N
        TXTID.setForeground(new java.awt.Color(0, 0, 0));
        TXTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTID.setEnabled(false);
        jPanel1.add(TXTID);
        TXTID.setBounds(250, 10, 110, 25);

        TXTAge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTAge);
        TXTAge.setBounds(250, 380, 110, 20);

        TXTSSN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTSSN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTSSN);
        TXTSSN.setBounds(200, 70, 160, 19);

        TXTTele.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTTele.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTTele);
        TXTTele.setBounds(200, 100, 160, 19);

        TXTAdress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTAdress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTAdress);
        TXTAdress.setBounds(180, 130, 180, 19);

        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTName);
        TXTName.setBounds(250, 40, 110, 19);

        TXTSocial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTSocial);
        TXTSocial.setBounds(250, 160, 110, 19);

        TXTSalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTSalary);
        TXTSalary.setBounds(250, 190, 110, 19);

        TXTJob.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTJob.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTJob);
        TXTJob.setBounds(250, 220, 110, 19);

        TXTUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(TXTUser);
        TXTUser.setBounds(250, 260, 110, 19);

        ShowPass.setText("SP");
        ShowPass.setOpaque(false);
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass);
        ShowPass.setBounds(210, 340, 50, 30);

        ShowPass1.setText("SP");
        ShowPass1.setOpaque(false);
        ShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPass1ActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass1);
        ShowPass1.setBounds(210, 290, 50, 30);

        TXTPass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTPass);
        TXTPass.setBounds(210, 290, 150, 30);

        jLabel14.setText("تأكيد كلمة السر");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 350, 100, 15);

        TXTConfirm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTConfirm);
        TXTConfirm.setBounds(210, 340, 150, 30);

        LBLImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(LBLImage);
        LBLImage.setBounds(10, 40, 150, 130);

        BTNUpload.setText("رفع الصورة");
        BTNUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUploadActionPerformed(evt);
            }
        });
        jPanel1.add(BTNUpload);
        BTNUpload.setBounds(30, 180, 104, 25);

        BTNCancel.setText("الغاء البيانات");
        BTNCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCancel);
        BTNCancel.setBounds(20, 350, 120, 30);

        BTNSave.setText("احفظ البيانات");
        BTNSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSaveActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSave);
        BTNSave.setBounds(20, 300, 120, 30);

        LBLMess.setForeground(new java.awt.Color(204, 0, 51));
        LBLMess.setText("كلمة المرور غير متطابقة");
        jPanel1.add(LBLMess);
        LBLMess.setBounds(280, 320, 150, 15);

        jLabel1.setText("تسجيل بيانات الموظف");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 346, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String URL;
    private void BTNUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUploadActionPerformed
        try {
            URL = Tools.GetAnyPhoto(BTNUpload, LBLImage, 160, 130);
        } catch(Exception ex)
        {
            System.out.println("Sorry We Didn't Get Image");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_BTNUploadActionPerformed

    private void BTNSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSaveActionPerformed
        
        if (TXTName.getText().equals("") || TXTSSN.getText().equals("") || TXTTele.getText().equals("")
                || TXTAdress.getText().equals("") || TXTSocial.getText().equals("") || TXTSalary.getText().equals("")
                || TXTJob.getText().equals("") || TXTUser.getText().equals("") || TXTPass.getText().equals("")
                || TXTConfirm.getText().equals("") || TXTAge.getText().equals("") || URL == null)
        {
            Tools.myMess("ارجوك املئ كل البيانات");
        }
        else
        {
            try {
                Integer.parseInt(TXTTele.getText());
                if (TXTTele.getText().length() != 11)
                {
                    Tools.myMess("ارجوك ادخل رقم التليفون المكون من احد عشر خانة");
                    TXTTele.setText("");
                    TXTTele.requestFocus();
                }
                else
                {
                    if (!TXTPass.getText().equals(TXTConfirm.getText()))
                    {
                        LBLMess.setVisible(true);
                        TXTPass.setText("");
                        TXTConfirm.setText("");
                        TXTPass.requestFocus();
                    }
                    else
                    {
                        int ID = Integer.parseInt(TXTID.getText());
                        String Name = TXTName.getText();
                        long SSN = Long.parseLong(TXTSSN.getText());
                        String Tele = TXTTele.getText().trim();
                        String Address = TXTAdress.getText();
                        String SC = TXTSocial.getText();
                        int Salary = Integer.parseInt(TXTSalary.getText());
                        String JD = TXTJob.getText();
                        String userName = TXTUser.getText();
                        String Pass = TXTPass.getText();
                        int Age = Integer.parseInt(TXTAge.getText());
                        URL = URL.replace("//", "////");
                        String Photo = URL;
                        
                        
                        Employee em = new Employee();
                        em.setId(ID);
                        em.setName(Name);
                        em.setSSN(SSN);
                        em.setTele(Tele);
                        em.setAdress(Address);
                        em.setSM(SC);
                        em.setSalary(Salary);
                        em.setJD(JD);
                        em.setUserName(userName);
                        em.setPassWord(Pass);
                        em.setAge(Age);
                        em.setPhoto(Photo);
                        
                        em.add();
                        TXTID.setText(Go.countautonumber("Employee", "id"));
                           
                    }
                }
            } catch(NumberFormatException ex)
            {
                Tools.myMess("أكتب رقم تليفون صحيح");
                TXTTele.setText("");
                TXTTele.requestFocus();
                System.out.println(ex.getMessage());
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_BTNSaveActionPerformed

    private void BTNCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelActionPerformed
        
        int a = JOptionPane.showConfirmDialog(null, "هل تريد الإلغاء؟", "الإلغاء", JOptionPane.YES_NO_OPTION);
        if (a == 0)
        {
            TXTName.setText("");
            TXTSSN.setText("");
            TXTTele.setText("");
            TXTAdress.setText("");
            TXTSocial.setText("");
            TXTSalary.setText("");
            TXTJob.setText("");
            TXTUser.setText("");
            TXTPass.setText("");
            TXTConfirm.setText("");
            TXTAge.setText("");
            TXTName.requestFocus();
        }
    }//GEN-LAST:event_BTNCancelActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        if (ShowPass.isSelected())
        {
            TXTConfirm.setEchoChar((char)0);
        }
        else
        {
            TXTConfirm.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    private void ShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPass1ActionPerformed
        if (ShowPass1.isSelected())
        {
            TXTPass.setEchoChar((char)0);
        }
        else
        {
            TXTPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ShowPass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNCancel;
    private controls.JMybotton BTNSave;
    private controls.JMybotton BTNUpload;
    private javax.swing.JLabel LBLImage;
    private javax.swing.JLabel LBLMess;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JCheckBox ShowPass1;
    private javax.swing.JTextField TXTAdress;
    private javax.swing.JTextField TXTAge;
    private javax.swing.JPasswordField TXTConfirm;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTJob;
    private javax.swing.JTextField TXTName;
    private javax.swing.JPasswordField TXTPass;
    private javax.swing.JTextField TXTSSN;
    private javax.swing.JTextField TXTSalary;
    private javax.swing.JTextField TXTSocial;
    private javax.swing.JTextField TXTTele;
    private javax.swing.JTextField TXTUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
