/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class EmployeeCataloge extends javax.swing.JFrame {

    /**
     * Creates new form Cataloge
     */
    public EmployeeCataloge() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLBackGround, 600, 320);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Panal = new javax.swing.JPanel();
        BTNSeate = new controls.JMybotton();
        BTNReservation = new controls.JMybotton();
        BTNDetectName = new controls.JMybotton();
        BTNOffer = new controls.JMybotton();
        LBLBackGround = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LBLImage = new javax.swing.JLabel();
        LBLName = new javax.swing.JLabel();
        BTNSignout = new controls.JMybotton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuReservation = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuSeate = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuInternal3 = new javax.swing.JMenu();
        MenuUpdate3 = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panal.setLayout(null);

        BTNSeate.setText("عدد المقاعد المتاحه");
        BTNSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeateActionPerformed(evt);
            }
        });
        Panal.add(BTNSeate);
        BTNSeate.setBounds(428, 190, 152, 40);

        BTNReservation.setText("الحجز");
        BTNReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReservationActionPerformed(evt);
            }
        });
        Panal.add(BTNReservation);
        BTNReservation.setBounds(30, 80, 120, 40);

        BTNDetectName.setText("كشوفات الرحلات");
        BTNDetectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDetectNameActionPerformed(evt);
            }
        });
        Panal.add(BTNDetectName);
        BTNDetectName.setBounds(10, 180, 140, 40);

        BTNOffer.setText("العروض");
        BTNOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOfferActionPerformed(evt);
            }
        });
        Panal.add(BTNOffer);
        BTNOffer.setBounds(470, 80, 110, 40);

        LBLBackGround.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        LBLBackGround.setOpaque(true);
        Panal.add(LBLBackGround);
        LBLBackGround.setBounds(0, 0, 600, 320);

        jLabel1.setText("اقسام البرنامج المخصصة للموظف");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("مرحباً يا ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 0, 60, 30);

        LBLImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBLImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(LBLImage);
        LBLImage.setBounds(250, 0, 30, 30);

        LBLName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(LBLName);
        LBLName.setBounds(150, 0, 90, 30);

        BTNSignout.setText("تسجيل الخروج");
        BTNSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSignoutActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSignout);
        BTNSignout.setBounds(10, 0, 130, 30);

        MenuFile.setText("ملف");

        MenuReservation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        MenuReservation.setText("الحجز");
        MenuReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservationActionPerformed(evt);
            }
        });
        MenuFile.add(MenuReservation);

        MenuAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        MenuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Admin.png"))); // NOI18N
        MenuAdmin.setText("الإنتقال إلى المدير");
        MenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdminActionPerformed(evt);
            }
        });
        MenuFile.add(MenuAdmin);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuFile.add(MenuOffer);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        jMenuItem5.setText("الكراسى المتاحه والشاغره");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuFile.add(jMenuItem5);

        MenuSeate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuSeate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        MenuSeate.setText("عدد الكراسى المتاحه");
        MenuSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSeateActionPerformed(evt);
            }
        });
        MenuFile.add(MenuSeate);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuFile.add(MenuCalculator);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuExit);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuFile.add(MenuNote);

        jMenuBar1.add(MenuFile);

        MenuInternal3.setText("تعديل");

        MenuUpdate3.setText("تعديل حجز رحلة داخلية");
        MenuUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdate3ActionPerformed(evt);
            }
        });
        MenuInternal3.add(MenuUpdate3);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        MenuInternal3.add(MenduExternal);

        jMenuItem3.setText("تعديل حجز رحلة خارجية");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuInternal3.add(jMenuItem3);

        jMenuBar1.add(MenuInternal3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(Panal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Panal, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void BTNReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReservationActionPerformed
        Tools.openForm(new TypeOfCustomers());
       this.dispose();
    }//GEN-LAST:event_BTNReservationActionPerformed

    private void MenuReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservationActionPerformed
        Tools.openForm(new TypeOfCustomers());
       this.dispose();
    }//GEN-LAST:event_MenuReservationActionPerformed

    private void MenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdminActionPerformed
       Tools.openForm(new AdminLogin1());
       this.dispose();
    }//GEN-LAST:event_MenuAdminActionPerformed

    private void MenuUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdate3ActionPerformed
        Tools.openForm(new InternalUpdate());
        this.dispose();

    }//GEN-LAST:event_MenuUpdate3ActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
        this.dispose();
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tools.openForm(new ExternalUpdate());
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void BTNSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeateActionPerformed
        Tools.openForm(new SeateNumber());
    }//GEN-LAST:event_BTNSeateActionPerformed

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
        this.dispose();
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void BTNDetectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDetectNameActionPerformed
        Tools.openForm(new FlightStatement());
        this.dispose();
    }//GEN-LAST:event_BTNDetectNameActionPerformed

    private void MenuSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSeateActionPerformed
        Tools.openForm(new SeateAvailbale());
    }//GEN-LAST:event_MenuSeateActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Tools.openForm(new SeateNumber());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BTNSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSignoutActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "هل تريد تسجيل الخروج؟","تأكيد",JOptionPane.YES_NO_OPTION);
        if (x == 0)
        {
            Tools.openForm(new MainForm());
            this.dispose();
        }
    }//GEN-LAST:event_BTNSignoutActionPerformed

    private void BTNOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_BTNOfferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeCataloge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeCataloge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNDetectName;
    private controls.JMybotton BTNOffer;
    private controls.JMybotton BTNReservation;
    private controls.JMybotton BTNSeate;
    private controls.JMybotton BTNSignout;
    private javax.swing.JLabel LBLBackGround;
    public static javax.swing.JLabel LBLImage;
    public static javax.swing.JLabel LBLName;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuAdmin;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInternal3;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenuItem MenuReservation;
    private javax.swing.JMenuItem MenuSeate;
    private javax.swing.JMenuItem MenuUpdate3;
    private javax.swing.JPanel Panal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
