/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.External;
import Classes.Internal;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class ExternalSektion extends javax.swing.JFrame {

    /**
     * Creates new form InterpalSektion
     */
    External ex = new External();
    Internal in = new Internal();
    public ExternalSektion() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLImage, 608, 277);
        groupButton();
        ComboOffer.addItem("");
        ex.fillComboBox(ComboOffer);
        TXTCash.setDisabledTextColor(Color.BLACK);
    }
    private String Cash;
    private String URL;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTPassport = new controls.JTextBox(160);
        jLabel3 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(160);
        jLabel4 = new javax.swing.JLabel();
        TXTTele = new controls.JTextBox(160);
        jLabel6 = new javax.swing.JLabel();
        TXTChair = new controls.JTextBox(160);
        R2 = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        ComboOffer = new controls.JMyCompo();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BTNCancel = new controls.JMybotton();
        BTNReserv = new controls.JMybotton();
        LBLIco = new javax.swing.JLabel();
        BTNUpload = new controls.JMybotton();
        jLabel11 = new javax.swing.JLabel();
        TXTCash = new controls.JTextBox(160);
        LBLImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuSeate = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuReservation = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        MenuInternal = new javax.swing.JMenu();
        MenuUpdate = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("املئ البيانتات لاكمال الحجز");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("رقم الباسبور");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 50, 79, 15);

        TXTPassport.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTPassport.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTPassport);
        TXTPassport.setBounds(350, 50, 160, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الأسم");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 20, 40, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNameActionPerformed(evt);
            }
        });
        jPanel1.add(TXTName);
        TXTName.setBounds(350, 20, 160, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم التليفون");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 80, 79, 15);

        TXTTele.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTTele);
        TXTTele.setBounds(350, 80, 160, 19);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ارقام الكراسى");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 180, 90, 20);

        TXTChair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTChair.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(TXTChair);
        TXTChair.setBounds(340, 180, 160, 19);

        R2.setText("لا");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        jPanel1.add(R2);
        R2.setBounds(400, 110, 50, 23);

        R1.setText("تعم");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        jPanel1.add(R1);
        R1.setBounds(460, 110, 50, 23);

        ComboOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOfferActionPerformed(evt);
            }
        });
        jPanel1.add(ComboOffer);
        ComboOffer.setBounds(350, 140, 160, 24);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("تم الدفع");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 110, 60, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("أسم العرض");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(520, 140, 70, 20);

        BTNCancel.setText("الغاء الأمر");
        jPanel1.add(BTNCancel);
        BTNCancel.setBounds(130, 240, 100, 25);

        BTNReserv.setText("أكد الحجز");
        BTNReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReservActionPerformed(evt);
            }
        });
        jPanel1.add(BTNReserv);
        BTNReserv.setBounds(360, 240, 90, 25);

        LBLIco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(LBLIco);
        LBLIco.setBounds(10, 10, 150, 120);

        BTNUpload.setText("ارفع صوره");
        BTNUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUploadActionPerformed(evt);
            }
        });
        jPanel1.add(BTNUpload);
        BTNUpload.setBounds(20, 140, 130, 25);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("السعر النهائى");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(500, 210, 90, 20);

        TXTCash.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTCash.setEnabled(false);
        jPanel1.add(TXTCash);
        TXTCash.setBounds(340, 210, 160, 19);

        LBLImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(LBLImage);
        LBLImage.setBounds(0, 0, 608, 277);

        MenuFile.setText("ملف");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        jMenuItem1.setText("أختر كرسى");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuFile.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("الأستعلامات");
        MenuFile.add(jMenuItem5);

        MenuSeate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuSeate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        MenuSeate.setText("عدد الكراسى المتاحه");
        MenuSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSeateActionPerformed(evt);
            }
        });
        MenuFile.add(MenuSeate);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuFile.add(MenuCalculator);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuFile.add(MenuNote);

        MenuReservation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation.setText("رجوغ");
        MenuReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservationActionPerformed(evt);
            }
        });
        MenuFile.add(MenuReservation);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        MenuInternal.setText("تعديل");

        MenuUpdate.setText("تعديل حجز رحلة داخلية");
        MenuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateActionPerformed(evt);
            }
        });
        MenuInternal.add(MenuUpdate);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        MenuInternal.add(MenduExternal);

        jMenuItem2.setText("تعديل حجز رحلة خارجية");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuInternal.add(jMenuItem2);

        jMenuBar1.add(MenuInternal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservationActionPerformed
        Tools.openForm(new EmployeeCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservationActionPerformed

    private void groupButton()
    {
        ButtonGroup g = new ButtonGroup();
        g.add(R1);
        g.add(R2);
    }
    
    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateActionPerformed
        Tools.openForm(new InternalUpdate());
    }//GEN-LAST:event_MenuUpdateActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tools.openForm(new SeateNumber3());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BTNReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReservActionPerformed
         if (TXTName.getText().equals("") || TXTPassport.getText().equals("") || TXTTele.getText().equals("")
                || ComboOffer.getSelectedItem().equals("") || TXTChair.getText().equals(""))
        {
            Tools.myMess("املئ كل البيانات من فضلك");
        }
        else
        {
            ex.setOffer_code(ex.getTripeCode(ComboOffer));
            if (ex.count() == 47)
            {
                Tools.myMess("تمت حجز الرحلة بالكامل");
                int x = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                if (x == 0)
                {
                    Tools.openForm(new FlightStatement());
                    this.dispose();
                }
            }
            else
            {
                if (TXTPassport.getText().length() != 9)
                {
                    Tools.myMess("اكتب رقم الباسبور صالح");
                    TXTPassport.setText("");
                    TXTPassport.requestFocus();
                }
                else
                {
                    ex.setName(TXTName.getText());
                    ex.setSSN(TXTPassport.getText());
                    ex.setTele(TXTTele.getText());
                    ex.setCash(Cash);
                    ex.setOffer_code(ex.getTripeCode(ComboOffer));
                    ex.setSeate(Integer.parseInt(TXTChair.getText()));
                    URL = URL.replace("\\", "\\\\");
                    ex.setPhoto(URL);

                    if (ex.quary() == true)
                    {
                        Tools.myMess("هذا الكرسى تم حجزه بالفعل");
                        TXTChair.setText("");
                        TXTChair.requestFocus();
                    }
                    else
                    {
                        int x = JOptionPane.showConfirmDialog(null, "هل لديك مرافقين؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                        if (x == 0)
                        {
                            ex.add();
                            Tools.openForm(new AccompanyingPage());
                            AccompanyingPage.Panel.setSelectedIndex(2);
                            AccompanyingPage.TXTParent2.setText(TXTPassport.getText());
                            AccompanyingPage.TXTOffer2.setText(String.valueOf(ex.getTripeCode(ComboOffer)));
                        }
                        else
                        {
                            ex.add();
                            TXTCash.setText(ex.Quary());
                            // chooce the loaction to save the reseite
                            String path = null;
                            JFileChooser ch = new JFileChooser();
                            ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                            int y = ch.showSaveDialog(this);

                            if (y == JFileChooser.APPROVE_OPTION)
                            {
                                path = ch.getSelectedFile().toString();
                            }
                            try {
                                PrintWriter ws = new PrintWriter(path+".txt");
                                ws.println(" ---------------- The final coast you will cash it -------------------- ");
                                ws.println(" The Result is "+ 1 * Integer.parseInt(TXTCash.getText()));
                                ws.println(" The Resete was written by "+in.getEmp_name() + " and");
                                ws.println(" It was printed in "+Tools.PrintDate());
                                ws.close();
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(InternalSektion.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BTNReservActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        Cash = "نعم";
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        Cash = "لا";
    }//GEN-LAST:event_R2ActionPerformed

    private void BTNUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUploadActionPerformed
        URL = Tools.GetAnyPhoto(BTNUpload, LBLIco, 150, 120);
    }//GEN-LAST:event_BTNUploadActionPerformed

    private void TXTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNameActionPerformed

    private void ComboOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOfferActionPerformed
        
    }//GEN-LAST:event_ComboOfferActionPerformed

    private void MenuSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSeateActionPerformed
        Tools.openForm(new SeateAvailbaleExternal());
    }//GEN-LAST:event_MenuSeateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExternalSektion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNCancel;
    private controls.JMybotton BTNReserv;
    private controls.JMybotton BTNUpload;
    private controls.JMyCompo ComboOffer;
    private javax.swing.JLabel LBLIco;
    private javax.swing.JLabel LBLImage;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInternal;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuReservation;
    private javax.swing.JMenuItem MenuSeate;
    private javax.swing.JMenuItem MenuUpdate;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    public static javax.swing.JTextField TXTCash;
    public static javax.swing.JTextField TXTChair;
    public static javax.swing.JTextField TXTName;
    private javax.swing.JTextField TXTPassport;
    private javax.swing.JTextField TXTTele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
