/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.gard;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class Gard extends javax.swing.JFrame {

    /**
     * Creates new form Salary
     */
    public Gard() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLBack, 915, 388);
        gard.fillEmployee(JTableEmployee, "Employee", 0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableEmployee = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMybotton1 = new controls.JMybotton();
        LBLBack = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuReservation = new javax.swing.JMenu();
        MenuEmployee = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuReservation3 = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuUpdate1 = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("صفحة جرد الارباح");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(790, 10, 110, 15);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الموظفين ومرتباتهم");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 123, 15);

        JTableEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اسم الموظف", "المرتب"
            }
        ));
        jScrollPane1.setViewportView(JTableEmployee);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 400, 230);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 40, 430, 290);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("الرحلات و الارباح القادمة");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(130, 10, 150, 15);

        jTable2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اسم الرحلة", "عدد المشتركين", "الأرباح"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 40, 400, 230);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(470, 40, 430, 290);

        jMybotton1.setText("أطبع كشف الجرد كاملاً");
        jPanel2.add(jMybotton1);
        jMybotton1.setBounds(360, 350, 170, 25);

        LBLBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(LBLBack);
        LBLBack.setBounds(0, 0, 915, 388);

        MenuReservation.setText("ملف");

        MenuEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        MenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/business-01-512.png"))); // NOI18N
        MenuEmployee.setText("اضافة موظفين");
        MenuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmployeeActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuEmployee);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        jMenuItem4.setText("الحجز");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuReservation.add(jMenuItem4);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuOffer);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuNote);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuCalculator);

        MenuReservation3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation3.setText("رجوغ");
        MenuReservation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservation3ActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuReservation3);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuReservation.add(MenuExit);

        jMenuBar1.add(MenuReservation);

        jMenu1.setText("تعديل");

        jMenuItem6.setText("تغير باسورد المدير");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("تغير بيانات موظف");
        jMenu1.add(jMenuItem7);

        MenuUpdate1.setText("تعديل حجز رحلة داخلية");
        MenuUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdate1ActionPerformed(evt);
            }
        });
        jMenu1.add(MenuUpdate1);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        jMenu1.add(MenduExternal);

        jMenuItem3.setText("تعديل حجز رحلة خارجية");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmployeeActionPerformed
        Tools.openForm(new EmployeeSignUp());
        this.dispose();
    }//GEN-LAST:event_MenuEmployeeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Tools.openForm(new TypeOfCustomers());
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdate1ActionPerformed
        Tools.openForm(new InternalUpdate());
    }//GEN-LAST:event_MenuUpdate1ActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuReservation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservation3ActionPerformed
        Tools.openForm(new AdminCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservation3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableEmployee;
    private javax.swing.JLabel LBLBack;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuEmployee;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenu MenuReservation;
    private javax.swing.JMenuItem MenuReservation3;
    private javax.swing.JMenuItem MenuUpdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private controls.JMybotton jMybotton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
