/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Internal;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class InternalSektion extends javax.swing.JFrame {

    /**
     * Creates new form InterpalSektion
     */
    Internal in = new Internal();
    public InternalSektion() {
        initComponents();
        Tools.setIcon("src/Photo/TouristLogo.jpg", LBLImage, 518, 278);
        ComboOffer.addItem("");
        in.fillComboBox(ComboOffer); 
        groupButton();
        TXTFinalCoast.setDisabledTextColor(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTSSN = new controls.JTextBox(160);
        jLabel3 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(160);
        jLabel4 = new javax.swing.JLabel();
        TXTTelephone = new controls.JTextBox(160);
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new controls.JTextBox(160);
        jLabel6 = new javax.swing.JLabel();
        TXTChair = new controls.JTextBox(160);
        Radio2 = new javax.swing.JRadioButton();
        Radio1 = new javax.swing.JRadioButton();
        ComboOffer = new controls.JMyCompo();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BTNCancel = new controls.JMybotton();
        BTNReserve = new controls.JMybotton();
        jLabel10 = new javax.swing.JLabel();
        TXTFinalCoast = new controls.JTextBox(160);
        LBLImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuSeate = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuReservation = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        MenuInternal = new javax.swing.JMenu();
        MenuUpdate = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("املئ البيانات لاكمال الحجز");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الرقم القومى");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(428, 50, 82, 15);

        TXTSSN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTSSN);
        TXTSSN.setBounds(260, 50, 160, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الأسم");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 20, 40, 15);

        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTName);
        TXTName.setBounds(310, 20, 160, 19);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم التليفون");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 80, 79, 15);

        TXTTelephone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTTelephone);
        TXTTelephone.setBounds(260, 80, 160, 19);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("رقم التليفون");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 80, 79, 15);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(260, 80, 160, 19);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ارقام الكراسى");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 180, 90, 20);

        TXTChair.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(TXTChair);
        TXTChair.setBounds(250, 180, 160, 19);

        Radio2.setText("لا");
        Radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio2ActionPerformed(evt);
            }
        });
        jPanel1.add(Radio2);
        Radio2.setBounds(310, 110, 50, 23);

        Radio1.setText("تعم");
        Radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1ActionPerformed(evt);
            }
        });
        jPanel1.add(Radio1);
        Radio1.setBounds(370, 110, 50, 23);

        ComboOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboOfferActionPerformed(evt);
            }
        });
        jPanel1.add(ComboOffer);
        ComboOffer.setBounds(260, 140, 160, 24);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("تم الدفع");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 110, 60, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("أسم العرض");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 140, 70, 20);

        BTNCancel.setText("الغاء الأمر");
        jPanel1.add(BTNCancel);
        BTNCancel.setBounds(10, 220, 100, 25);

        BTNReserve.setText("أكد الحجز");
        BTNReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReserveActionPerformed(evt);
            }
        });
        jPanel1.add(BTNReserve);
        BTNReserve.setBounds(10, 180, 90, 25);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("السعر النهائى");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 210, 90, 20);

        TXTFinalCoast.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTFinalCoast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTFinalCoast.setEnabled(false);
        jPanel1.add(TXTFinalCoast);
        TXTFinalCoast.setBounds(250, 210, 160, 19);

        LBLImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(LBLImage);
        LBLImage.setBounds(0, 0, 518, 250);

        MenuFile.setText("ملف");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        jMenuItem1.setText("أختر كرسى");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuFile.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("الأستعلامات");
        MenuFile.add(jMenuItem5);

        MenuSeate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuSeate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        MenuSeate.setText("عدد الكراسى المتاحه");
        MenuSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSeateActionPerformed(evt);
            }
        });
        MenuFile.add(MenuSeate);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuFile.add(MenuCalculator);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuFile.add(MenuNote);

        MenuReservation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation.setText("رجوغ");
        MenuReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservationActionPerformed(evt);
            }
        });
        MenuFile.add(MenuReservation);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        MenuInternal.setText("تعديل");

        MenuUpdate.setText("تعديل حجز رحلة داخلية");
        MenuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateActionPerformed(evt);
            }
        });
        MenuInternal.add(MenuUpdate);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        MenuInternal.add(MenduExternal);

        jMenuItem2.setText("تعديل حجز رحلة خارجية");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuInternal.add(jMenuItem2);

        jMenuBar1.add(MenuInternal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 360, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservationActionPerformed
        Tools.openForm(new EmployeeCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservationActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateActionPerformed
        Tools.openForm(new InternalUpdate());

    }//GEN-LAST:event_MenuUpdateActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void groupButton ()
    {
        ButtonGroup g1 = new ButtonGroup();
        g1.add(Radio1);
        g1.add(Radio2);
    }
    
    String a ;
    
    private void BTNReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReserveActionPerformed
        if (TXTName.getText().equals("") || TXTSSN.getText().equals("") || TXTTelephone.getText().equals("")
                || TXTChair.getText().equals("") || ComboOffer.getSelectedItem().equals(""))
        {
            Tools.myMess("ارجوك املئ كل البيانات");
        }
        else
        {
            in.setOffer_code(in.getTripeCode(ComboOffer));
            if (in.count() == 47)
            {
                Tools.myMess("تمت حجز الرحلة بالكامل");
                int x = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                if (x == 0)
                {
                    Tools.openForm(new FlightStatement());
                    this.dispose();
                }
            }
            else
            {
                if (TXTSSN.getText().length() == 14)
            {
                try {
                    
                    Integer.parseInt(TXTTelephone.getText());
                    if (TXTTelephone.getText().length() != 11)
                    {
                        Tools.myMess("من فضلك اكتر رقم التليفون المكون من احد عشر رقم");
                        TXTTelephone.requestFocus();
                    }
                    else
                    {
                        String Name = TXTName.getText();
                        long SSN = Long.parseLong(TXTSSN.getText());
                        String Tele = TXTTelephone.getText();
                        int y1 = in.getTripeCode(ComboOffer);
                        int Offer = y1;
                        int seate = Integer.parseInt(TXTChair.getText());
                        
                        int x = JOptionPane.showConfirmDialog(null, "هل لديك مرافقين" , "تأكيد" , JOptionPane.YES_NO_OPTION);
                        if (x == 0)
                        {
                            in.setName(Name);
                            in.setSSN(SSN);
                            in.setTele(Tele);
                            in.setCash(a);
                            in.setOffer_code(Offer);
                            in.setSeate(seate);
                            if (in.quary() == true)
                                Tools.myMess("اسف هذا الكرسة مجحوز من قبل");
                            else    
                            {
                                in.add();
                                Tools.openForm(new AccompanyingPage());
                                AccompanyingPage.TXTParent.setText(TXTSSN.getText());
                                AccompanyingPage.TXTCode.setText(String.valueOf(in.getTripeCode(ComboOffer)));
                            }
                        }
                        else
                        {
                            in.setName(Name);
                            in.setSSN(SSN);
                            in.setTele(Tele);
                            in.setCash(a);
                            in.setOffer_code(Offer);
                            in.setSeate(seate);
                            if (in.quary() == true)
                            {
                               Tools.myMess("اسف هذا الكرسة مجحوز من قبل");
                            }
                            else
                            {
                                in.add();
                                TXTFinalCoast.setText(in.Quary());
                                // chooce the loaction to save the reseite
                                String path = null;
                                JFileChooser ch = new JFileChooser();
                                ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                                int y = ch.showSaveDialog(this);

                                if (y == JFileChooser.APPROVE_OPTION)
                                {
                                    path = ch.getSelectedFile().toString();
                                }
                                try {
                                    PrintWriter ws = new PrintWriter(path+".txt");
                                    ws.println(" ---------------- The final coast you will cash it -------------------- ");
                                    ws.println(" The Result is "+ 1 * Integer.parseInt(TXTFinalCoast.getText()));
                                    ws.println(" ---------------------------------------------------------------------- ");
                                    ws.println(" The Resete was written by "+in.getEmp_name() + " and");
                                    ws.println(" It was printed in "+Tools.PrintDate());
                                    ws.close();
                                } catch (FileNotFoundException ex) {
                                    System.err.println(ex.getMessage());
                                }
                            }
                        }
                    }
                    
                } catch (NumberFormatException ex)
                    {
                        Tools.myMess("من فضلك اكتب رقم تلبفون صالح");
                    }
                }
                else
                {
                    Tools.myMess("اكتب الرقم القومى الصالح من اربعه عشر رقم");
                }
            }
            
        }
    }//GEN-LAST:event_BTNReserveActionPerformed

    private void Radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1ActionPerformed
        a = "نعم";
    }//GEN-LAST:event_Radio1ActionPerformed

    private void Radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio2ActionPerformed
        a = "ﻻ";
    }//GEN-LAST:event_Radio2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tools.openForm(new SeateNumber1());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ComboOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboOfferActionPerformed
        
    }//GEN-LAST:event_ComboOfferActionPerformed

    private void MenuSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSeateActionPerformed
        Tools.openForm(new SeateAvailbaleInternal());
    }//GEN-LAST:event_MenuSeateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternalSektion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InternalSektion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNCancel;
    private controls.JMybotton BTNReserve;
    private controls.JMyCompo ComboOffer;
    private javax.swing.JLabel LBLImage;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuInternal;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuReservation;
    private javax.swing.JMenuItem MenuSeate;
    private javax.swing.JMenuItem MenuUpdate;
    private javax.swing.JRadioButton Radio1;
    private javax.swing.JRadioButton Radio2;
    public static javax.swing.JTextField TXTChair;
    public static javax.swing.JTextField TXTFinalCoast;
    public static javax.swing.JTextField TXTName;
    private javax.swing.JTextField TXTSSN;
    private javax.swing.JTextField TXTTelephone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
