/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Accompanying;
import Classes.Internal;
import DataBase.Go;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class InternalUpdate extends javax.swing.JFrame {

    /**
     * Creates new form InternalUpdate
     */
    Internal in = new Internal();
    Accompanying ac = new Accompanying();
    
    public InternalUpdate() {
        initComponents();
        ComboOffer.addItem("");
        in.fillComboBox(ComboOffer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableParent1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAccom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(150);
        jLabel3 = new javax.swing.JLabel();
        TXTSSN = new controls.JTextBox(210);
        jLabel4 = new javax.swing.JLabel();
        TXTTele = new controls.JTextBox(150);
        TXTCash = new controls.JTextBox(150);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTChair = new controls.JTextBox(150);
        BTNUpdate = new controls.JMybotton();
        BTNAdd = new controls.JMybotton();
        BTNSearch = new controls.JMybotton();
        ComboOffer = new controls.JMyCompo();
        LBL1 = new javax.swing.JLabel();
        TXTSSN1 = new controls.JTextBox(150);
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuChair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuOffer = new javax.swing.JMenuItem();
        MenuSeate = new javax.swing.JMenuItem();
        MenuNote = new javax.swing.JMenuItem();
        MenuCalculator = new javax.swing.JMenuItem();
        MenuReservation3 = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuPrint = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("تعديل بيانتات الحجز لرحلة داخلية");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        TableParent1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TableParent1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الأسم", "الرقم القومى", "رقم التليفون", "تم الدفع", "رقم العرض", "رقم الكرسى"
            }
        ));
        TableParent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableParent1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableParent1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 600, 110);

        TableAccom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TableAccom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الأسم", "الرقم القومى", "رقم التليفون", "رقم العرض", "رقم الكرسى"
            }
        ));
        TableAccom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAccomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAccom);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 600, 260);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الاسم");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(760, 50, 40, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTName);
        TXTName.setBounds(620, 70, 150, 19);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("الرقم القومى");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(540, 20, 90, 15);

        TXTSSN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TXTSSN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSSNActionPerformed(evt);
            }
        });
        jPanel1.add(TXTSSN);
        TXTSSN.setBounds(330, 20, 210, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم التليفون");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(720, 90, 90, 15);

        TXTTele.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTele.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTTele);
        TXTTele.setBounds(620, 110, 150, 19);

        TXTCash.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTCash);
        TXTCash.setBounds(620, 160, 150, 19);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("تم الدفع");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(750, 140, 60, 15);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("رقم العرض");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(740, 180, 70, 15);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("رقم الكرسى");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(730, 230, 80, 15);

        TXTChair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTChair.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(TXTChair);
        TXTChair.setBounds(620, 250, 150, 19);

        BTNUpdate.setText("تحديث البيانات");
        BTNUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BTNUpdate);
        BTNUpdate.setBounds(670, 330, 123, 50);

        BTNAdd.setText("أضافة مرافق");
        BTNAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddActionPerformed(evt);
            }
        });
        jPanel1.add(BTNAdd);
        BTNAdd.setBounds(670, 390, 120, 50);

        BTNSearch.setText("احضر بيانات العميل");
        BTNSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSearchActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSearch);
        BTNSearch.setBounds(160, 20, 160, 25);
        jPanel1.add(ComboOffer);
        ComboOffer.setBounds(622, 200, 150, 24);

        LBL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBL1.setText("الرقم القومى");
        jPanel1.add(LBL1);
        LBL1.setBounds(720, 270, 90, 15);

        TXTSSN1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTSSN1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTSSN1);
        TXTSSN1.setBounds(620, 290, 150, 19);

        MenuChair.setText("ملف");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        jMenuItem1.setText("أختر كرسى");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuChair.add(jMenuItem1);

        MenuOffer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuOffer.setText("الأستعلامات");
        MenuOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOfferActionPerformed(evt);
            }
        });
        MenuChair.add(MenuOffer);

        MenuSeate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuSeate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Seate.png"))); // NOI18N
        MenuSeate.setText("عدد الكراسى المتاحه");
        MenuSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSeateActionPerformed(evt);
            }
        });
        MenuChair.add(MenuSeate);

        MenuNote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote.setText("ملاحظات");
        MenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNoteActionPerformed(evt);
            }
        });
        MenuChair.add(MenuNote);

        MenuCalculator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        MenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/calculator.png"))); // NOI18N
        MenuCalculator.setText("اله حاسبة");
        MenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCalculatorActionPerformed(evt);
            }
        });
        MenuChair.add(MenuCalculator);

        MenuReservation3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuReservation3.setText("رجوغ");
        MenuReservation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservation3ActionPerformed(evt);
            }
        });
        MenuChair.add(MenuReservation3);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit.setText("خروج");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuChair.add(MenuExit);

        jMenuBar1.add(MenuChair);

        jMenu1.setText("طباعه");

        MenuPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        MenuPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/print-logo.png"))); // NOI18N
        MenuPrint.setText("طباعه فاتورة");
        MenuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrintActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPrint);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOfferActionPerformed
        Tools.openForm(new Offers());
    }//GEN-LAST:event_MenuOfferActionPerformed

    private void MenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNoteActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNoteActionPerformed

    private void MenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCalculatorActionPerformed
        Tools.openForm(new Calculator());
    }//GEN-LAST:event_MenuCalculatorActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuReservation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservation3ActionPerformed
        Tools.openForm(new EmployeeCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuReservation3ActionPerformed

    private int i = 0;
    DefaultTableModel model;
    
    private void setModel ()
    {
        model = (DefaultTableModel) TableParent1.getModel();
    }
    
    private void setModel1 ()
    {
        model = (DefaultTableModel) TableAccom.getModel();
    }
    
    private void TableAccomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAccomMouseClicked
        setModel1();
        i = TableAccom.getSelectedRow();
        TXTName.setText(model.getValueAt(i, 0).toString());
        TXTTele.setText(model.getValueAt(i, 2).toString());
        TXTChair.setText(model.getValueAt(i, 4).toString());
        in.setOffer_code(Integer.parseInt(model.getValueAt(i, 3).toString()));
        ComboOffer.setSelectedItem(in.getTripeName());
        TXTName.requestFocus();
    }//GEN-LAST:event_TableAccomMouseClicked

    private void TableParent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableParent1MouseClicked
        setModel();
        i = TableParent1.getSelectedRow();
        TXTName.setText(model.getValueAt(i, 0).toString());
        TXTTele.setText(model.getValueAt(i, 2).toString());
        TXTCash.setText(model.getValueAt(i, 3).toString());
        TXTChair.setText(model.getValueAt(i, 5).toString());
        in.setOffer_code(Integer.parseInt(model.getValueAt(i, 4).toString()));
        ComboOffer.setSelectedItem(in.getTripeName());
        TXTName.requestFocus();
    }//GEN-LAST:event_TableParent1MouseClicked

    private void BTNSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSearchActionPerformed
        long a = Long.parseLong(TXTSSN.getText());
        in.setSSN(a);
        ac.setPSSN1(a);
        in.getOneRow(TableParent1, "Internal_Reservarion", 0, 0);
        ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
    }//GEN-LAST:event_BTNSearchActionPerformed

    private void BTNUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUpdateActionPerformed
        
        /*
            dictionary
            first if :- وظيفتها انها تعرف انى بعمل ابتديد على اول جدول ولا تانى
            second if :- اتأكد امتى اعمل check للكرسى فى حالة تغير الكرسى
            third if :- للتأكد من الكرسى مشغول ام لا
        
            ونفس الكلام مع الجدول التانى
        */
        
        if (TXTCash.getText().equals(""))
        {
            setModel1();
            ac.setSSN(Long.parseLong(model.getValueAt(i, 1).toString()));
            ac.setName(TXTName.getText());
            ac.setTele(TXTTele.getText());
            ac.setOffer_code(in.getTripeCode(ComboOffer));
            ac.setSeate(Integer.parseInt(TXTChair.getText()));
            
            if (!TXTChair.getText().equals(model.getValueAt(i, 4).toString()))
            {
                if (ac.quary() == true)
                {
                    Tools.myMess("هذا الكرسة محجوز بالفعل");
                    TXTChair.setText("");
                    TXTChair.requestFocus();
                }
                else
                {
                    ac.update();
                    ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
                    setClear();
                }
            }
            else
            {
                ac.update();
                ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
                setClear();
            }
            
            
        }
        else
        {
            setModel();
            in.setSSN(Long.parseLong(TXTSSN.getText()));
            in.setName(TXTName.getText());
            in.setTele(TXTTele.getText());
            in.setCash(TXTCash.getText());
            in.setOffer_code(in.getTripeCode(ComboOffer));
            in.setSeate(Integer.parseInt(TXTChair.getText()));
            
            if (!TXTChair.getText().equals(model.getValueAt(i, 5).toString()))
            {
                if (in.quary() == true)
                {
                    Tools.myMess("هذا الكرسة محجوز بالفعل");
                    TXTChair.setText("");
                    TXTChair.requestFocus();
                }
                else
                {
                    in.update();
                    in.getOneRow(TableParent1, "Internal_Reservarion", 0, 0);
                    String Sql = "Update Accompanying set offerCode = "+ in.getTripeCode(ComboOffer) 
                            + " Where PSSN1 = "+Long.parseLong(TXTSSN.getText())+";";
                    Go.ExecuteNonQuerey(Sql);
                    ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
                    setClear();
                }
            }
            else
            {
                in.update();
                in.getOneRow(TableParent1, "Internal_Reservarion", 0, 0);
                String Sql = "Update Accompanying set offerCode = "+ in.getTripeCode(ComboOffer)
                        + " Where PSSN1 = "+Long.parseLong(TXTSSN.getText())+";";
                Go.ExecuteNonQuerey(Sql);
                ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
                setClear();
            }
            
        }
    }//GEN-LAST:event_BTNUpdateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Tools.openForm(new SeateNumber1());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrintActionPerformed
        in.setOffer_code(in.getTripeCode(ComboOffer));
        int price = Integer.parseInt(in.Quary());
        int count = Integer.parseInt(ac.count()) + 1;
        int Res = price * count;
        
        // print the final cash to two method one of theme to the GUI and two to the file Recete
        //InteralSektion.TXTFinalCoast.setText(String.valueOf(price*count));
        
        String path = null;
        JFileChooser ch = new JFileChooser();
        ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int y = ch.showSaveDialog(this);
        
        if (y == JFileChooser.APPROVE_OPTION)
        {
            path = ch.getSelectedFile().toString();
        }
        try {
            // form table one get the coast for the parent
            setModel();
            PrintWriter ws = new PrintWriter(path+".txt");
            ws.println(" ---------------- The final coast you will cash it -------------------- ");
            ws.println("Person number 1  : "+model.getValueAt(0, 0).toString() + "    " +" his price "+price +" $ ");
            
            // from table Accom get the coast of the person
            setModel1();
            for (int i=0 ; i< model.getRowCount() ; i++)
            {
                ws.println("Person number "+ i+2 +" : "+ model.getValueAt(i, 0) + "    " +" his price "+price +" $ ");
            }
            ws.println("-------------------------------------------------------------------------");
            ws.println(" The Final Cash is "+ Res + " $");
            ws.println(" The Resete was written by "+in.getEmp_name() + " and");
            ws.println(" It was printed in "+Tools.PrintDate());
            ws.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InternalSektion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuPrintActionPerformed

    private void BTNAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddActionPerformed
        int x =JOptionPane.showConfirmDialog(null, "هل تريد اضافة مرافق؟", "تأكيد", JOptionPane.YES_NO_OPTION);
        if (x == 0)
        {
            in.setOffer_code(in.getTripeCode(ComboOffer));
            if (in.count() == 47)
            {
                Tools.myMess("تمت حجز الرحلة بالكامل");
                int y = JOptionPane.showConfirmDialog(null, "هل تريد طباعة كشف الرحلة؟", "تأكيد", JOptionPane.YES_NO_OPTION);
                if (y == 0)
                {
                    Tools.openForm(new FlightStatement());
                    this.dispose();
                }
            }
            else
            {
                ac.setSSN(Long.parseLong(TXTSSN1.getText()));
                ac.setName(TXTName.getText());
                ac.setTele(TXTTele.getText());
                ac.setOffer_code(in.getTripeCode(ComboOffer));
                ac.setSeate(Integer.parseInt(TXTChair.getText()));
                ac.setPSSN1(Long.parseLong(TXTSSN.getText()));
                ac.add();
                ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
            }
        }
    }//GEN-LAST:event_BTNAddActionPerformed

    private void TXTSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSSNActionPerformed
        long a = Long.parseLong(TXTSSN.getText());
        in.setSSN(a);
        ac.setPSSN1(a);
        in.getOneRow(TableParent1, "Internal_Reservarion", 0, 0);
        ac.getOneRow1(TableAccom, "Accompanying", 0, 0);
    }//GEN-LAST:event_TXTSSNActionPerformed

    private void MenuSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSeateActionPerformed
        Tools.openForm(new SeateAvailbaleInternal());
    }//GEN-LAST:event_MenuSeateActionPerformed

    private void setClear()
    {
        TXTName.setText("");
        TXTTele.setText("");
        TXTCash.setText("");
        ComboOffer.setSelectedItem("");
        TXTChair.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternalUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternalUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternalUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternalUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InternalUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNAdd;
    private controls.JMybotton BTNSearch;
    private controls.JMybotton BTNUpdate;
    private controls.JMyCompo ComboOffer;
    private javax.swing.JLabel LBL1;
    private javax.swing.JMenuItem MenuCalculator;
    private javax.swing.JMenu MenuChair;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuNote;
    private javax.swing.JMenuItem MenuOffer;
    private javax.swing.JMenuItem MenuPrint;
    private javax.swing.JMenuItem MenuReservation3;
    private javax.swing.JMenuItem MenuSeate;
    private javax.swing.JTextField TXTCash;
    public static javax.swing.JTextField TXTChair;
    private javax.swing.JTextField TXTName;
    private javax.swing.JTextField TXTSSN;
    private javax.swing.JTextField TXTSSN1;
    private javax.swing.JTextField TXTTele;
    private javax.swing.JTable TableAccom;
    private javax.swing.JTable TableParent1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
