/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.ComponentOrientation;
import tourism.company.Tools;
import Classes.Note1;

/**
 *
 * @author mohamed
 */
public class Note extends javax.swing.JFrame {

    /**
     * Creates new form Note
     */
    public Note() {
        initComponents();
        TXTNote.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }
    
    Note1 n = new Note1();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTTitle = new controls.JTextBox(120);
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTNote = new javax.swing.JTextArea();
        BTNSave = new controls.JMybotton();
        BTNLoad = new controls.JMybotton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel1.setLayout(null);

        jLabel2.setText("عنوان الملاحظه");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(421, 20, 100, 15);

        TXTTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTTitle.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TXTTitle);
        TXTTitle.setBounds(220, 20, 190, 19);

        TXTNote.setColumns(20);
        TXTNote.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTNote.setRows(5);
        jScrollPane1.setViewportView(TXTNote);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(23, 60, 490, 190);

        BTNSave.setText("حفظ");
        BTNSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSaveActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSave);
        BTNSave.setBounds(320, 260, 65, 25);

        BTNLoad.setText("أعرض ملاحظه");
        BTNLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoadActionPerformed(evt);
            }
        });
        jPanel1.add(BTNLoad);
        BTNLoad.setBounds(147, 260, 117, 25);

        jLabel1.setText("أكتب ملاحظاتك هنا");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 418, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSaveActionPerformed
        if (TXTTitle.getText().equals("") || TXTNote.getText().equals(""))
            Tools.myMess("ارجوك املئ كل الحقول");
        else
        {
            n.setTitle(TXTTitle.getText());
            n.setNote(TXTNote.getText());
            
            // add to database
            n.Add();
            TXTNote.setText("");
            TXTTitle.setText("");
        }
    }//GEN-LAST:event_BTNSaveActionPerformed

    private void BTNLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoadActionPerformed
        Tools.openForm(new ChooceNote());
    }//GEN-LAST:event_BTNLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Note.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Note().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNLoad;
    private controls.JMybotton BTNSave;
    public static javax.swing.JTextArea TXTNote;
    public static javax.swing.JTextField TXTTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
