/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Classes.Itinerary;
import java.awt.Color;
import java.awt.ComponentOrientation;
import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class Offers extends javax.swing.JFrame {

    /**
     * Creates new form Offers
     */
    Itinerary in = new Itinerary();
    public Offers() {
        initComponents();
        Tools.setIcon("src/Photo/logo-2.png", LBLImage, LBLImage.getWidth(), LBLImage.getHeight()+1);
        ComboCode.addItem("");
        in.fillcombobox(ComboCode);
        TXTDescrib.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        TXTDescrib.setDisabledTextColor(Color.BLACK);
        TXTName.setDisabledTextColor(Color.BLACK);
        TXTCoast.setDisabledTextColor(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ComboCode = new controls.JMyCompo();
        BTNShow = new controls.JMybotton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTDescrib = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TXTCoast = new controls.JTextBox(190);
        jLabel4 = new javax.swing.JLabel();
        TXTName = new controls.JTextBox(190);
        jLabel5 = new javax.swing.JLabel();
        LBLImage = new javax.swing.JLabel();
        BTNSeate = new controls.JMybotton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("أختر اسم العرض :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(431, 10, 130, 15);
        jPanel1.add(ComboCode);
        ComboCode.setBounds(132, 30, 300, 24);

        BTNShow.setText("أعرض التفاصيل");
        BTNShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNShowActionPerformed(evt);
            }
        });
        jPanel1.add(BTNShow);
        BTNShow.setBounds(220, 70, 130, 25);

        TXTDescrib.setColumns(20);
        TXTDescrib.setRows(5);
        TXTDescrib.setEnabled(false);
        jScrollPane1.setViewportView(TXTDescrib);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 220, 330, 170);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("التفاصيل");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 190, 80, 15);

        TXTCoast.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTCoast.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTCoast.setEnabled(false);
        jPanel1.add(TXTCoast);
        TXTCoast.setBounds(280, 160, 190, 19);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("اسم الرحلة");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 130, 70, 15);

        TXTName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TXTName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXTName.setEnabled(false);
        jPanel1.add(TXTName);
        TXTName.setBounds(280, 130, 190, 19);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("السعر للفرد");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 160, 80, 15);

        LBLImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(LBLImage);
        LBLImage.setBounds(30, 80, 160, 140);

        BTNSeate.setText("أعرض الكراسى");
        BTNSeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeateActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSeate);
        BTNSeate.setBounds(10, 370, 130, 25);

        jLabel1.setText("العروض المتوفرة حاليا التى تقدمها شركتنا وحصريا");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNShowActionPerformed
        in.setTrip_Name(ComboCode.getSelectedItem().toString());
        int code = in.getTripeCode();
        
        
        in.setTrip_code(code);
        in.getOffer(TXTCoast, TXTName, TXTDescrib, LBLImage, 160, 140);
    }//GEN-LAST:event_BTNShowActionPerformed

    private void BTNSeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeateActionPerformed
        Tools.openForm(new SeateNumber4());
    }//GEN-LAST:event_BTNSeateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Offers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Offers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybotton BTNSeate;
    private controls.JMybotton BTNShow;
    public static controls.JMyCompo ComboCode;
    private javax.swing.JLabel LBLImage;
    private javax.swing.JTextField TXTCoast;
    private javax.swing.JTextArea TXTDescrib;
    private javax.swing.JTextField TXTName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
