/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import tourism.company.Tools;

/**
 *
 * @author mohamed
 */
public class UpdateReservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public UpdateReservation() {
        initComponents();
        Tools.setIcon("src/Photo/EgyptLogo.png", BTNinternal, 150, 130);
        Tools.setIcon("src/Photo/umrah.jpg", BTNUmrah, 150, 130);
        Tools.setIcon("src/Photo/ExternalTourrism.jpg", BTNoutward, 150, 130);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BTNoutward = new javax.swing.JButton();
        BTNinternal = new javax.swing.JButton();
        BTNUmrah = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuFile1 = new javax.swing.JMenu();
        MenuReservation1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuNote1 = new javax.swing.JMenuItem();
        MenuBack = new javax.swing.JMenuItem();
        MenuExit1 = new javax.swing.JMenuItem();
        MenuInternal = new javax.swing.JMenu();
        MenuUpdate = new javax.swing.JMenuItem();
        MenduExternal = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("احجز نوع رحلتك");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));
        jPanel1.setLayout(null);

        BTNoutward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNoutwardActionPerformed(evt);
            }
        });
        jPanel1.add(BTNoutward);
        BTNoutward.setBounds(380, 20, 150, 130);

        BTNinternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNinternalActionPerformed(evt);
            }
        });
        jPanel1.add(BTNinternal);
        BTNinternal.setBounds(20, 20, 150, 130);

        BTNUmrah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUmrahActionPerformed(evt);
            }
        });
        jPanel1.add(BTNUmrah);
        BTNUmrah.setBounds(200, 20, 150, 130);

        MenuFile1.setText("ملف");

        MenuReservation1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuReservation1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/reservation.png"))); // NOI18N
        MenuReservation1.setText("الحجز");
        MenuReservation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservation1ActionPerformed(evt);
            }
        });
        MenuFile1.add(MenuReservation1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("الأستعلامات");
        MenuFile1.add(jMenuItem6);

        MenuNote1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/note.png"))); // NOI18N
        MenuNote1.setText("ملاحظات");
        MenuNote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNote1ActionPerformed(evt);
            }
        });
        MenuFile1.add(MenuNote1);

        MenuBack.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uplogo.png"))); // NOI18N
        MenuBack.setText("رجوع");
        MenuBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBackActionPerformed(evt);
            }
        });
        MenuFile1.add(MenuBack);

        MenuExit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit.png"))); // NOI18N
        MenuExit1.setText("خروج");
        MenuExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExit1ActionPerformed(evt);
            }
        });
        MenuFile1.add(MenuExit1);

        jMenuBar2.add(MenuFile1);

        MenuInternal.setText("تعديل");

        MenuUpdate.setText("تعديل حجز رحلة داخلية");
        MenuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateActionPerformed(evt);
            }
        });
        MenuInternal.add(MenuUpdate);

        MenduExternal.setText("تعديل حجز رحلة عمره");
        MenduExternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenduExternalActionPerformed(evt);
            }
        });
        MenuInternal.add(MenduExternal);

        jMenuItem2.setText("تعديل حجز رحلة خارجية");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuInternal.add(jMenuItem2);

        jMenuBar2.add(MenuInternal);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 455, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuReservation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservation1ActionPerformed
        Tools.openForm(new UpdateReservation());
        this.dispose();
    }//GEN-LAST:event_MenuReservation1ActionPerformed

    private void MenuExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExit1ActionPerformed
        Tools.ConfirmExit();
    }//GEN-LAST:event_MenuExit1ActionPerformed

    private void MenuNote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNote1ActionPerformed
        Tools.openForm(new Note());
    }//GEN-LAST:event_MenuNote1ActionPerformed

    private void MenuBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBackActionPerformed
        Tools.openForm(new EmployeeCataloge());
        this.dispose();
    }//GEN-LAST:event_MenuBackActionPerformed

    private void BTNinternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNinternalActionPerformed
        Tools.openForm(new InternalUpdate());
        this.dispose();
    }//GEN-LAST:event_BTNinternalActionPerformed

    private void BTNUmrahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUmrahActionPerformed
        Tools.openForm(new UmrahUpdate());
        this.dispose();
    }//GEN-LAST:event_BTNUmrahActionPerformed

    private void BTNoutwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNoutwardActionPerformed
        Tools.openForm(new ExternalUpdate());
        this.dispose();
    }//GEN-LAST:event_BTNoutwardActionPerformed

    private void MenuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateActionPerformed
        Tools.openForm(new InternalUpdate());
        
    }//GEN-LAST:event_MenuUpdateActionPerformed

    private void MenduExternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenduExternalActionPerformed
        Tools.openForm(new UmrahUpdate());
    }//GEN-LAST:event_MenduExternalActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tools.openForm(new ExternalUpdate());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNUmrah;
    private javax.swing.JButton BTNinternal;
    private javax.swing.JButton BTNoutward;
    private javax.swing.JMenuItem MenduExternal;
    private javax.swing.JMenuItem MenuBack;
    private javax.swing.JMenuItem MenuExit1;
    private javax.swing.JMenu MenuFile1;
    private javax.swing.JMenu MenuInternal;
    private javax.swing.JMenuItem MenuNote1;
    private javax.swing.JMenuItem MenuReservation1;
    private javax.swing.JMenuItem MenuUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
